### ISSUE TITLE
Web: Back Office การค้นหาศูนย์เรียนรู้ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#1]
@cmmadnat 
น้องแนตคะ การค้นหาศูนย์เรียนรู้ตามแนวพระราชดำริ ใช้เงื่อนไข จังหวัดอย่างเดียว  ไม่แสดงผลข้อมูลเลยคะ ตามภาพ
![image](https://user-images.githubusercontent.com/31124544/32263156-139824e0-bf0b-11e7-9914-40e8faa0e0e8.png)

**Comment by cmmadnat** [comment]
รบกวนทดสอบใหม่ครับ 
<img width="1280" alt="screen shot 2560-11-02 at 15 11 15" src="https://user-images.githubusercontent.com/37333/32315779-2060c1ca-bfe0-11e7-8300-f18b7cfce7ec.png">
