### ISSUE TITLE
Back :ศูนย์เรียนรู้ตามแนวพระราชดำริ -หน้าจอบันทึกข้อมูลสถานที่ตั้ง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#10]
น้องแนต  @cmmadnat รบกวนปรับตามภาพ

![image](https://user-images.githubusercontent.com/31124544/32321370-7bf48a40-bff3-11e7-88fd-c2b4df293d7e.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32479279-9ecd8316-c3bb-11e7-8c7c-00f382bb7948.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
