### ISSUE TITLE
Back : ศ. ตามแนวพระราชดำริ บันทึกข้อมูลเสร็จแล้ว ยกเลิก หน้าจอรายการไม่แสดงผล

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#100]
1. เมื่อบันทึกข้อมูลเรียบร้อย ครั้งแรกไม่แจ้งว่าบันทึกเรียบร้อย
![image](https://user-images.githubusercontent.com/30930235/32951078-3774fcee-cbdb-11e7-9c19-ba410dcd9ea5.png)

2. เมื่อกดปุ่มยกเลิกครั้งแรก ระบบขยับหน้า แต่ไม่กลับไปหน้าแสดงรายการ

3. เมื่อกดปุ่มยกเลิกอีกครั้ง ระบบกลับไปที่หน้าจอแสดงรายการ แต่ไม่แสดงรายการข้อมูลที่บันทึกใหม่
![image](https://user-images.githubusercontent.com/30930235/32951202-abac3cb2-cbdb-11e7-80c6-c8c9aab8f759.png)

**Comment by cmmadnat** [comment]
https://www.youtube.com/watch?v=jslosONTQno&feature=youtu.be

**Comment by Srikridsadaporn** [comment]
เรียบร้อยตามน้องบอลบอก
