### ISSUE TITLE
Back : ศ. ตามแนวพระราชดำริ หน้าบันทึกข้อมูล กรณีเพิ่มใหม่ แสดงค่า Default อำเภอ ตำบล ไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#101]
ที่ถูกต้องยังไม่ควรมีค่า Default ก่อน จนกว่าจะบันทึกจังหวัด

![image](https://user-images.githubusercontent.com/30930235/32951312-0f4146f0-cbdc-11e7-849b-5d42f8cb7fe0.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32988875-c172b408-cd3f-11e7-8125-33f6cafb614c.png)

**Comment by anucha1892** [comment]
แนต ยังแก้ไม่ถูกต้องนะครับ 
ในกรณีที่ยังไม่เลือกจังหวัด ช่องอำเภอ/เขต , ตำบล/แขวง ต้องเป็นช่องว่าง จนกว่าจะเลือกจังหวัดแล้วถึงจะแสดงในช่องว่า "=เลือก="

**Comment by Srikridsadaporn** [comment]
เรียบร้อย ปิดค่ะ
