### ISSUE TITLE
Back : ศ. พอเพียง ปรับหน้าจอแสดงรายการข้อมูลก่อนระบุเงื่อนไขใหม่ 

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#102]
![image](https://user-images.githubusercontent.com/30930235/32951660-507fe8fa-cbdd-11e7-889b-8c08dfc3124e.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32988634-76725bb6-cd3a-11e7-9484-4a086150e30a.png)

**Comment by anucha1892** [comment]
![102](https://user-images.githubusercontent.com/33414080/32998981-d151773c-cdd1-11e7-89a3-dc65cb2ac690.PNG)

**Comment by RDPB2-Kuer** [comment]
OK
