### ISSUE TITLE
Back : ศ. พอเพียง เพิ่มข้อมูลใหม่ ระบบไม่แสดงกล่องบันทึกเรียบร้อย

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#103]
![image](https://user-images.githubusercontent.com/30930235/32952124-d61d35a2-cbde-11e7-94b5-d0a66f4ce9cf.png)

**Comment by RDPB2-Kuer** [comment]
5. เมื่อกดปุ่ม ยกเลิก ระบบแสดงกล่องบันทึกเรียบร้อย อีกครั้ง ซึ่งไม่ถูกต้อง

**Comment by RDPB2-Kuer** [comment]
โดยสรุป การแสดงผลข้อมูลหลังจากกดปุ่ม ยกเลิก ยังไม่ถูกต้อง

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-19 03-37-44](https://user-images.githubusercontent.com/37333/32984539-15768fbc-ccdb-11e7-9ef6-14183b3e8790.png)

**Comment by anucha1892** [comment]
หน้าเพิ่มข้อมูลใหม่ ฟิลด์บังคับ * ถ้าไม่ได้ใส่ข้อมูล ให้ขึ้นกรอบสีเหลืองเหมือนหน้าปรับปรุงข้อมูล
![103](https://user-images.githubusercontent.com/33414080/32999599-ad0ac91a-cdd5-11e7-8161-9c861376b9ca.PNG)

**Comment by anucha1892** [comment]
![103-1](https://user-images.githubusercontent.com/33414080/33000003-f2176f66-cdd7-11e7-8490-f3ad81765bb7.PNG)

**Comment by RDPB2-Kuer** [comment]
OK
