### ISSUE TITLE
Back : ศ. พอเพียง กดปุ่มบันทึก 2 ครั้ง ระบบบันทึก 2 รายการ ซึ่งไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#104]
![image](https://user-images.githubusercontent.com/30930235/32952445-ee8726ba-cbdf-11e7-93dd-d39781a13745.png)

**Comment by cmmadnat** [comment]
แก้ไขให้ขึ้นแล้วครับ

**Comment by anucha1892** [comment]
เรียบร้อยครับ

**Comment by RDPB2-Kuer** [comment]
OK

**Comment by anucha1892** [comment]
ยังไม่เรียบร้อยครับ
![104](https://user-images.githubusercontent.com/33414080/33000217-509e2e02-cdd9-11e7-8ae7-ed6618a5b517.PNG)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
