### ISSUE TITLE
  Back : ศ. ศึกษาพัฒนา ขอปรับแก้การแสดงข้อมูลทั่วไป

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#105]
![image](https://user-images.githubusercontent.com/30930235/32952838-fd093dd0-cbe0-11e7-8213-c9719e637d79.png)

**Comment by RDPB2-Kuer** [comment]
ขอเปลี่ยนจาก "Email Address" เป็น "อีเมลล์"

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-19 02-25-03](https://user-images.githubusercontent.com/37333/32984030-dfbb626c-ccd0-11e7-949c-96698ee603bf.png)

**Comment by RDPB2-Kuer** [comment]
OK
