### ISSUE TITLE
Back : ศ. ศึกษาพัฒนา ปรับแก้หน้าจอแสดงรายการใหม่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#106]
![image](https://user-images.githubusercontent.com/30930235/32952980-6558ea48-cbe1-11e7-8be9-84995a43e9a1.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-19 02-22-24](https://user-images.githubusercontent.com/37333/32984005-8070d79c-ccd0-11e7-8ad8-5562ed6ca12e.png)

**Comment by RDPB2-Kuer** [comment]
OK
