### ISSUE TITLE
  Back : ศ. อื่นๆ หน้าแสดงรายการ และบันทึกข้อมูล แสดงชื่อหน่วยงานไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#107]
![image](https://user-images.githubusercontent.com/30930235/32954319-5092a348-cbe5-11e7-8b15-aa5476517375.png)

![image](https://user-images.githubusercontent.com/30930235/32954382-7cddd242-cbe5-11e7-866f-f66f2d6133c0.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-19 02-19-58](https://user-images.githubusercontent.com/37333/32983990-2f266c4e-ccd0-11e7-8a83-c168d577f4cc.png)
![screenshot from 2017-11-19 02-20-58](https://user-images.githubusercontent.com/37333/32983996-4e8a4a92-ccd0-11e7-8370-f67d5e0e131d.png)

**Comment by RDPB2-Kuer** [comment]
OK
