### ISSUE TITLE
Back : ศ. อื่นๆ - เลื่อนหัวข้อพิกัดอื่นๆ ให้ต่อท้ายพิกัดที่ตั้ง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#108]
![image](https://user-images.githubusercontent.com/30930235/32978535-bdf5aa34-cc76-11e7-983c-abfa0630b153.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-19 02-18-47](https://user-images.githubusercontent.com/37333/32983983-ff50dd1a-cccf-11e7-978d-d58768bcabbb.png)

**Comment by RDPB2-Kuer** [comment]
OK
