### ISSUE TITLE
Back : ศ. อื่นๆ ปรับปรุงส่วนบันทึกรูปแผนที่ตั้งศูนย์

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#109]
![image](https://user-images.githubusercontent.com/30930235/32978587-aa671240-cc77-11e7-924b-0e95e5b27af6.png)

**Comment by cmmadnat** [comment]
![Uploading Screenshot from 2017-11-19 02-16-16.png…]()

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-19 02-16-16](https://user-images.githubusercontent.com/37333/32983969-c58319d6-cccf-11e7-839a-e12781d91f6f.png)

**Comment by RDPB2-Kuer** [comment]
ยังมีเรื่องปุ่มเลือกภาพที่ยังไม่ได้แก้ ดังนี้

![image](https://user-images.githubusercontent.com/30930235/32999558-8c96382c-cdd5-11e7-8af7-ffe9515ae69d.png)

**Comment by cmmadnat** [comment]
<img width="436" alt="screen shot 2560-11-20 at 15 17 15" src="https://user-images.githubusercontent.com/37333/33008503-e96fa706-ce05-11e7-8cb3-43d9d33f33b9.png">

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
