### ISSUE TITLE
Back :ศูนย์เรียนรู้ตามแนวพระราชดำริ- หน้าจอรูปภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#11]
น้องแนตรบกวนปรับตามรายละเอียดในภาพ @cmmadnat  

![image](https://user-images.githubusercontent.com/31124544/32321459-c8843716-bff3-11e7-9b72-afcbf138e050.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32479335-e08ce9b8-c3bb-11e7-8a1b-f0695e6df5a6.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
