### ISSUE TITLE
ฺBack : ศูนย์เรียนรู้ตามแนวพระราชดำริฯ หน้าจอบันทึกขอมูล ตรวจสอบการคีย์ข้อมูลฟิลด์บังคับ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#110]
![image](https://user-images.githubusercontent.com/31124544/32978724-6e184c52-cc7a-11e7-9cad-88aa12344caa.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32979427-a8c8ebd8-cc87-11e7-8cf7-c1bcc8c5cdf8.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32979672-a1683858-cc8c-11e7-98a6-f8b8dfb4a0a7.png)

**Comment by RDPB2-Kuer** [comment]
รบกวนให้สีอ่อนลงกว่านี้ได้ไหมคะ เป็นสีเหลืองอ่อนนะคะ

**Comment by cmmadnat** [comment]
สีอ่อนลงแล้วครับ ตาม issue ในข้ออื่น
<img width="657" alt="screen shot 2560-11-20 at 15 15 34" src="https://user-images.githubusercontent.com/37333/33008453-ad0593fc-ce05-11e7-959c-9505d8ac1b38.png">

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
