### ISSUE TITLE
Back : ศ.ตามแนวพระราชดำริ หน้าจอบันทึกข้อมูล ปุ่มบันทึกข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#111]
ปุ่มบันทึกข้อมูล  เมื่อกดบันทึกข้อมูลแล้วมีข้อความแจ้งว่า "บันทึกข้อมูลเรียบร้อยแล้ว"   แต่มีข้อความเพิ่มอีกหนึ่งบรรทัดว่า "เลือกได้มากกว่า 1 รายการ" เข้ามาด้วย...รบกวนตรวจสอบด้วยคะ  
พี่ Print Screen ไม่ทัน

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32979140-56325ea4-cc82-11e7-82be-1220e82d4303.png)

**Comment by Srikridsadaporn** [comment]
![image](https://user-images.githubusercontent.com/31124544/32979295-220f340a-cc85-11e7-9494-78acf46863b5.png)

**Comment by RDPB2-Kuer** [comment]
พี่ลองบันทึก กดปุ่มครั้งแรก ไม่แสดงกล่อง ต้องกดปุ่มครั้งที่ 2 ถึงจะแสดงกล่อง

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32994006-92ee4b8e-cd93-11e7-9482-491c482e93ef.png)

**Comment by cmmadnat** [comment]
แก้แล้วครับ

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
