### ISSUE TITLE
Back : ศ. ตามแนว - ตรวจสอบ field บังคับไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#113]
![image](https://user-images.githubusercontent.com/30930235/32981215-14e3e99e-cca6-11e7-9588-0a7e4b216e57.png)
ขอให้ Highlight สีเหลืองอ่อน

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-19 02-12-06](https://user-images.githubusercontent.com/37333/32983922-10915e84-cccf-11e7-885e-7a628c899a26.png)

**Comment by RDPB2-Kuer** [comment]
การแสดงผลการตรวจสอบ field บังคับความเป็นมาตรฐานเดียวกัน แต่ทำไมกรณี field แรกไม่บันทึก ไม่แสดง highlight แต่มี pop up ตามภาพขึ้นแทน ขอให้ใช้เป็นแบบ Hightlight เหมือนกัน

![screen shot 2560-11-20 at 09 18 18](https://user-images.githubusercontent.com/30930235/32999373-4cd1e69c-cdd4-11e7-90ae-f3bd70ef6eae.png)

**Comment by cmmadnat** [comment]
เอาส่วนของ autocomplete ออกและไม่ยอมให้ผ่านไปครับ แต่ว่าสีคงจะทำไม่ได้

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
