### ISSUE TITLE
Back : ศ.อื่นๆ ปรับแก้ หน้าจอแสดงรายการ สถานะศูนย์เรียนรู้ (ด่วน)

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#114]
@cmmadnat 
น้องแนต  รบกวนปรับแก้ด่วน พี่จะ Capture หน้าจอส่ง กปร. ภายในวันนี้

![image](https://user-images.githubusercontent.com/31124544/32998941-9a5825be-cdd1-11e7-81f2-2737f40ca62f.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33000347-0c624678-cdda-11e7-9ae0-3fd5eb3cfd2a.png)

**Comment by anucha1892** [comment]
สถานะศูนย์เรียนรู้ ตกเป็น 3 บรรทัด ยังไม่ถูกต้องครับ
![114](https://user-images.githubusercontent.com/33414080/33004517-d5b033d2-cdf3-11e7-8fa1-1f11d0c300fe.PNG)

**Comment by cmmadnat** [comment]
<img width="548" alt="screen shot 2560-11-20 at 14 44 22" src="https://user-images.githubusercontent.com/37333/33007434-523cfedc-ce01-11e7-8c0e-4b420b0ca58e.png">

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
