### ISSUE TITLE
Back : ศ.อื่นๆ -หน้าบันทึกข้อมูล ตรวจสอบข้อมูลฟิลด์บังคับด้วย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#115]
![image](https://user-images.githubusercontent.com/31124544/32999952-b8febb1c-cdd7-11e7-99b5-61fb6fa5eaf8.png)

**Comment by cmmadnat** [comment]
<img width="1064" alt="screen shot 2560-11-20 at 14 40 20" src="https://user-images.githubusercontent.com/37333/33007306-c7078832-ce00-11e7-895b-84f20caaf733.png">

**Comment by anucha1892** [comment]
ฟิลด์บังคับ  "จังหวัด" ยังไม่ไฮไลท์สีเหลือง กรณียังไม่เลือก

**Comment by cmmadnat** [comment]
แก้เพิ่มแล้วครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
