### ISSUE TITLE
Back : ศ.อื่นๆ -หน้าบันทึกข้อมูล ตรวจสอบเลขบัตรประชาชน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#116]
![image](https://user-images.githubusercontent.com/31124544/33000111-af43f83e-cdd8-11e7-81bc-bd77714ad9c1.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33002733-99dfaa00-cde8-11e7-974a-bb3d59416a61.png)
เช็คตัวเลขและความยาว

**Comment by anucha1892** [comment]
ตรงเลขบัตรประชาชน ยังไม่มีการตรวจสอบ ซึ่งไม่ถูกต้อง

**Comment by Srikridsadaporn** [comment]
เรียบร้อย ปิด
