### ISSUE TITLE
Back : ปรับหน้า DashBord (ด่วน)

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#117]
![image](https://user-images.githubusercontent.com/31124544/33000460-ca228e20-cdda-11e7-881e-7163641130cd.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33002185-191962f6-cde5-11e7-8339-ef67a4a8a106.png)

**Comment by RDPB2-Kuer** [comment]
ยังไม่ถูกต้อง ขอปรับแก้อีกที ดังนี้
![image](https://user-images.githubusercontent.com/30930235/33005574-faf8fc28-cdf8-11e7-910e-085563af224a.png)

**Comment by cmmadnat** [comment]
<img width="1028" alt="screen shot 2560-11-20 at 14 32 18" src="https://user-images.githubusercontent.com/37333/33007100-b635d802-cdff-11e7-9fcd-5de1305990af.png">

**Comment by anucha1892** [comment]
เรียบร้อยครับ
