### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าเพิ่มข้อมูล แยกฟิลด์ เบอร์โทรศัพท์ เบอร์โทรสาร  

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#118]
แก้ไข ดังภาพ
![118](https://user-images.githubusercontent.com/33414080/33005678-7384ce38-cdf9-11e7-933d-ef636219cd8f.PNG)

**Comment by cmmadnat** [comment]
<img width="1280" alt="screen shot 2560-11-20 at 14 25 11" src="https://user-images.githubusercontent.com/37333/33006874-a60989ca-cdfe-11e7-896b-c745f8a8b754.png">

**Comment by anucha1892** [comment]
เรียบร้อยครับ
