### ISSUE TITLE
Back : ศ. อื่นๆ หน้าบันทึกข้อมูล ปรับแก้สถานที่ตั้งศูนย์เรียนรู้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#119]
![image](https://user-images.githubusercontent.com/31124544/33010629-c367f3e4-ce0d-11e7-9c49-f8802a5e0176.png)

**Comment by cmmadnat** [comment]
แก้ไขแล้วครับ

**Comment by cmmadnat** [comment]
<img width="676" alt="screen shot 2560-11-21 at 16 54 05" src="https://user-images.githubusercontent.com/37333/33065981-9ce21ff4-cedc-11e7-8255-cd13e5fa2d3b.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
