### ISSUE TITLE
Back :ศูนย์เรียนรู้ตามแนวพระราชดำริ-หน้าจอบันทึกข้อมูลเอกสารประกอบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#12]
น้องแนต @cmmadnat  รบกวนปรับตามรายละเอียดในภาพ 
![image](https://user-images.githubusercontent.com/31124544/32321536-013d8468-bff4-11e7-968e-6f05cbdae22f.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32479353-fedd725c-c3bb-11e7-99bc-1311621d49be.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
