### ISSUE TITLE
Back : ทุกศูนย์เรียนรู้ หน้ารายงาน เพิ่มข้อความยืนยัน "การลบ" 

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#120]
![120](https://user-images.githubusercontent.com/33414080/33011258-ffbcc23c-ce0f-11e7-9c74-2eee946ecd62.PNG)

**Comment by cmmadnat** [comment]
เพิ่ม popup แล้ว

**Comment by RDPB2-Kuer** [comment]
OK
