### ISSUE TITLE
Back : ศ. พอเพียง ขอปรับแก้การแสดงรายการ อีกหน่อย

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#121]
![image](https://user-images.githubusercontent.com/30930235/33050769-20cbc23c-ce99-11e7-8e2e-6e295727bbf9.png)

**Comment by cmmadnat** [comment]
<img width="468" alt="screen shot 2560-11-21 at 16 44 01" src="https://user-images.githubusercontent.com/37333/33065364-34acc732-cedb-11e7-9083-88cd5cd51397.png">
ลดขนาดลงมาเล็กน้อย

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
