### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง หน้าจอการบันทึกรูปภาพ เพิ่มข้อความบอกขนาดไฟล์ที่อัพโหลด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#122]
![image](https://user-images.githubusercontent.com/31124544/33054141-11b3205e-ceaa-11e7-94e7-1be0dfbd75d5.png)

**Comment by cmmadnat** [comment]
<img width="843" alt="screen shot 2560-11-21 at 16 42 20" src="https://user-images.githubusercontent.com/37333/33065274-f6bcc4e0-ceda-11e7-9db7-ff84da9b5d01.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
