### ISSUE TITLE
Back : ทุกศูนย์เรียนรู้ หน้าบันทึกข้อมูล  กรณีไม่ใส่ข้อมูลที่บังคับ ให้แสดงใต้ field สีแดงว่า “! บังคับใส่ข้อมูล”

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#123]
แก้ไข ตามภาพ
![122](https://user-images.githubusercontent.com/33414080/33054203-5fa2a5b4-ceaa-11e7-99e3-5491bd226073.PNG)

**Comment by cmmadnat** [comment]
เปลี่ยนแล้ว มีแล้วในทุกช่อง
<img width="967" alt="screen shot 2560-11-21 at 16 40 38" src="https://user-images.githubusercontent.com/37333/33065193-b94aa7d0-ceda-11e7-945a-6d5e70b1b70e.png">

**Comment by anucha1892** [comment]
ยังขึ้นไฮไลท์สีเหลืองอยู่เลยครับ
![image](https://user-images.githubusercontent.com/33414080/33065604-e6452200-cedb-11e7-9dc8-e8e272f72cec.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33085797-58505540-cf18-11e7-9e81-9c61b1a9ad09.png)
ปกตินะครับ

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
