### ISSUE TITLE
Back : ทุกศูนย์เรียนรู้ หน้าบันทึกข้อมูล  กรณีใส่ข้อมูลที่บังคับไม่ถูกต้อง ให้แสดงใต้ field สีแดงว่า “ ! ใส่ข้อมูลไม่ถูกต้อง”

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#124]
แก้ไข ตามภาพ
![123](https://user-images.githubusercontent.com/33414080/33054234-9460ad8c-ceaa-11e7-8b7a-72b8c487c37b.PNG)

**Comment by cmmadnat** [comment]
<img width="961" alt="screen shot 2560-11-21 at 16 39 39" src="https://user-images.githubusercontent.com/37333/33065132-96c4b71e-ceda-11e7-80b3-a92e939459f6.png">
มีเขียน และป็อปอัพเตือนชื่อซ้ำ

**Comment by anucha1892** [comment]
ทำไมแสดงไม่เหมือนกัน
![image](https://user-images.githubusercontent.com/33414080/33066032-bd6dedb6-cedc-11e7-961c-8c40e88f9511.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33085711-0ef07b00-cf18-11e7-96ad-4b1ba3b91082.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33085752-2c145c42-cf18-11e7-8325-9b6e9ba5866b.png)
ทดสอบใหม่ได้ไหมครับ ของผมปกตินะ

**Comment by RDPB2-Kuer** [comment]
ขอปรับแก้ใหม่ ดังนี้คะ
1. กรณีไม่ใส่ field ที่บังคับ ให้ขึ้นว่า
![image](https://user-images.githubusercontent.com/30930235/33104807-ba7ae5c0-cf5c-11e7-9330-752405bf1d85.png)

2. กรณีใส่ข้อมูลไม่ถูกต้อง ให้ขึ้นว่า
![image](https://user-images.githubusercontent.com/30930235/33104843-deb51c30-cf5c-11e7-964d-26146c93accc.png)

**Comment by RDPB2-Kuer** [comment]
หรือแบบนี้
![image](https://user-images.githubusercontent.com/30930235/33104875-0c69699c-cf5d-11e7-96bc-dd4ca60723e6.png)

เผื่อจะเอา icon ไปใช้
![image](https://user-images.githubusercontent.com/30930235/33104897-2a671bce-cf5d-11e7-8ff6-6749eb45e77e.png)

**Comment by Srikridsadaporn** [comment]
![image](https://user-images.githubusercontent.com/31124544/33108479-ed102272-cf6e-11e7-8fa1-4e687d730bbd.png)

**Comment by RDPB2-Kuer** [comment]
Please fill out this field ขอเปลี่ยนเป็น "กรุณาใส่ข้อมูลนี้"

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
