### ISSUE TITLE
ศ.ตามแนวพระราชดำริ  หน้าบันทึกข้อมูลรูปภาพ ปรับสีปุ่มลบทิ้ง และ ปรับข้อความบอกขนาดไฟล์ที่อัพโหลด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#125]
![image](https://user-images.githubusercontent.com/31124544/33054295-e26c93f6-ceaa-11e7-87b6-c0f6164fe8a0.png)

**Comment by cmmadnat** [comment]
<img width="810" alt="screen shot 2560-11-21 at 16 30 24" src="https://user-images.githubusercontent.com/37333/33064738-4b3d249e-ced9-11e7-9083-82a5253396fb.png">
น่าจะปรับไปแล้วนะครับ

**Comment by Srikridsadaporn** [comment]
ผิดหน้าค่ะ น้องแนต ศ.ตามแนวพระราชดำริ   ไม่ใช่ศูนย์เรียนรู้อื่นๆ 

![image](https://user-images.githubusercontent.com/31124544/33066697-a368d096-cede-11e7-9d97-ed6cd50a457d.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33085584-9efbe79e-cf17-11e7-9d32-be10db1cfafd.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33085602-ae7edb7c-cf17-11e7-806e-7a512376c38a.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
