### ISSUE TITLE
Back : ศ.อื่นๆ หน้าจอการบันทึกรูปภาพ เพิ่มข้อความบอกขนาดไฟล์ที่อัพโหลด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#126]
![image](https://user-images.githubusercontent.com/31124544/33054745-b477e57e-cead-11e7-9d78-c97dc85e5291.png)

**Comment by cmmadnat** [comment]
เพิ่มให้แล้วแบบเดียวกับ #127

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
