### ISSUE TITLE
Back : ศ.ศึกษาการพัฒนา ฯ หน้าจอการบันทึกรูปภาพ เพิ่มข้อความบอกขนาดไฟล์ที่อัพโหลด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#127]
![image](https://user-images.githubusercontent.com/31124544/33054777-fc3f4d02-cead-11e7-8911-cad24f802b01.png)

**Comment by cmmadnat** [comment]
<img width="787" alt="screen shot 2560-11-21 at 16 16 27" src="https://user-images.githubusercontent.com/37333/33064151-592fd490-ced7-11e7-9d55-cbf7de579ce6.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
