### ISSUE TITLE
Back : กรณีที่ user ใส่ข้อมูลด้วยตนเอง ให้มีปุ่มสำหรับลบข้อมูลให้ด้วย

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#128]
แบบมุมขวามือ
![s__5996584](https://user-images.githubusercontent.com/30930235/33056636-56ed16f2-ceb9-11e7-83f5-b6d178c32f35.jpg)

**Comment by cmmadnat** [comment]
<img width="529" alt="screen shot 2560-11-21 at 16 14 03" src="https://user-images.githubusercontent.com/37333/33064036-02d3bc56-ced7-11e7-944c-b34756fe5a60.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย  น้องแนตคะส่วนการอธิบายภาพ เอกสารประกอบ และรายละเอียดศูนย์เรียนรู้ไม่สามารถทำได้หรือคะ

**Comment by cmmadnat** [comment]
ในช่องใหญ่ไม่น่าจะได้ครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
