### ISSUE TITLE
ฺBack : ศูนย์เรียนรู้ตามแนวพระราชดำริฯ  ปรับการเลือกจังหวัด อำเภอ และตำบลในสถานที่ตั้งศูนย์

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#129]
![image](https://user-images.githubusercontent.com/31124544/33057529-0cdac7b2-cebe-11e7-872f-d0b62ad20d23.png)

**Comment by cmmadnat** [comment]
หมายความว่าจะให้ว่างไปเลยใช่ไหมครับ

**Comment by Srikridsadaporn** [comment]
คือศูนย์เรียนรู้ตามแนวพระราชดำริฯ ใช้ต่างจากแบบอื่นๆไงคะ ต้องปรับเป็นแบบเดียวกัน
 เมื่อเลือกชื่อจังหวัดแล้ว จึงมีคำว่า "=เลือก=" ที่อำเภอ ตำบลค่ะ

**Comment by cmmadnat** [comment]
Okay ครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
