### ISSUE TITLE
Back :ศูนย์เรียนรู้อื่นๆ - หน้าจอการแสดงรายการ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#13]
@cmmadnat  น้องแนต  รบกวนปรับตามรายละเอียดในภาพ 
![image](https://user-images.githubusercontent.com/31124544/32321575-2342dc48-bff4-11e7-8e2a-710c4bf28b78.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32487847-6848c0cc-c3dd-11e7-82b9-05b5597868aa.png)

**Comment by Srikridsadaporn** [comment]
ปิดไปก่อนนะ แล้วปรับรายละเอียดอีกที
