### ISSUE TITLE
Back : ศ.อื่นๆ ตรวจสอบ ",,,," เพิ่มในข้อมูลที่ตั้งศูนย์และข้อมูลการติดต่อเข้ามาโดยที่ไม่ได้พิมพ์

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#130]
![image](https://user-images.githubusercontent.com/31124544/33058519-8d982198-cec2-11e7-8896-e11605d05559.png)

**Comment by cmmadnat** [comment]
แปลกมาก ยังหาสาเหตุไม่ได้ แต่จะแก้ที่ปลายเหตุครับ

**Comment by cmmadnat** [comment]
แก้ไขที่ปลายเหตุแล้วครับ

**Comment by Srikridsadaporn** [comment]
ยังเป็นเหมือนเดิมค่ะ น้องแนต ,,, ยังมี

**Comment by cmmadnat** [comment]
ต้องกดบันทึกก่อนครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
