### ISSUE TITLE
Back : ศูนย์เรียนรู้ตามแนวพระราชดำริฯ หน้าแสดงรายการข้อมูล  ลบปุ่มลบทิ้งด้วย 1ปุ่ม (ลบปุ่มล่างนะ)

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#131]
![image](https://user-images.githubusercontent.com/31124544/33067624-4a1ae62a-cee1-11e7-90cb-1b7c45e8f98a.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33085455-4421d676-cf17-11e7-8e7c-566fbcfc332f.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
