### ISSUE TITLE
Back : ทุก ศ. - การตรวจสอบบังคับใส่ข้อมูลแรก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#132]
ขอให้เปลี่ยนการแสดงผลกรณีไม่บันทึกข้อมูล จาก "Please fill out this field" เป็น "กรุณาใส่ข้อมูลนี้"
![screen shot 2560-11-22 at 10 46 59](https://user-images.githubusercontent.com/30930235/33109156-9bb21012-cf72-11e7-877f-7b285148aeee.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33109806-3d79fd9e-cf76-11e7-8679-918990bdf87d.png)

**Comment by RDPB2-Kuer** [comment]
ทำของ ศ. ตามแนว ศ. อื่นๆ และศ. ศึกษา ให้ด้วยคะ

**Comment by RDPB2-Kuer** [comment]
ศ. พอเพียง เรียบร้อย

**Comment by Srikridsadaporn** [comment]
ศูนย์เรียนรู้ตามแนวพระราชดำริฯ  เรียบร้อย
ศูนย์เรียนรู้อื่นๆ เรียบร้อย
ศูนย์ศึกษาการพัฒนา ฯ เรียบร้อย
