### ISSUE TITLE
  Back : ทุก ศ. - การแสดง error กรณีไม่บันทึกข้อมูลบังคับไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#133]
เมื่อใส่ข้อมูลหัวข้อ ชื่อคน/ชื่อชุมชน แล้วกดปุ่มบันทึก ระบบจะต้องตรวจสอบและแสดง error กรณี user ไม่บันทึกข้อมูลที่บังคับ ดังนี้
![image](https://user-images.githubusercontent.com/30930235/33109481-4e6a4c28-cf74-11e7-9f6f-4ad201bc2f78.png)

![image](https://user-images.githubusercontent.com/30930235/33109599-171fbfcc-cf75-11e7-8927-73e972162cd0.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33111143-ef34462c-cf7e-11e7-8749-4597591c5365.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
