### ISSUE TITLE
Back : ทุก ศ. - การแสดง error กรณีบันทึกข้อมูลไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#134]
![image](https://user-images.githubusercontent.com/30930235/33109765-0d3a9f26-cf76-11e7-85a1-7040b86b165a.png)

**Comment by cmmadnat** [comment]
แก้พร้อมกันทั้งหมดแล้ว

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
