### ISSUE TITLE
Back : ทุก ศ. หน้าจอแสดงรายการ กรณีกดปุ่ม ลบทิ้ง แต่ไม่เลือกรายการ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#135]
![image](https://user-images.githubusercontent.com/30930235/33110026-a8846d76-cf77-11e7-8c10-302c3b4d4cd5.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
