### ISSUE TITLE
  Back : เพิ่มการแสดงหน้าจอ Login ก่อน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#136]
เมื่อระบุ url หลัก ให้ระบบแสดงหน้า Login ก่อน เมื่อกดปุ่ม ให้ระบบมาแสดงหน้า dashboard ก่อน

**Comment by RDPB2-Kuer** [comment]
และกรณีกดปุ่ม รายงาน ให้ระบบไม่ต้องทำงานต่อ

**Comment by cmmadnat** [comment]
ปรับแล้วครับ

**Comment by RDPB2-Kuer** [comment]
OK
