### ISSUE TITLE
Back : ศูนย์เรียนรู้อื่นๆ หน้าเพิ่มข้อมูล ยกเลิกการตรวจสอบฟิลด์ โทรศัพท์ และโทรสาร

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#137]
![image](https://user-images.githubusercontent.com/31124544/33110542-121ac494-cf7b-11e7-904d-b1294ccf79e9.png)

**Comment by Srikridsadaporn** [comment]
น้องแนต มันจะขึ้น " ,,, " เพิ่มเรื่อยๆ เมืีอมีการใส่ข้อมูลบังคับไม่ครบ  และกดบุ่มบันทึกในแต่ละครั้งจะมี ",," เพิ่มขึ้นมาในแต่ละครั้งที่บันทึก

**Comment by RDPB2-Kuer** [comment]
การแสดงข้อมูลหลังกด บันทึก ยังไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/33253423-e44cc4d2-d375-11e7-8c58-b41c0e2b38af.png)

**Comment by RDPB2-Kuer** [comment]
OK
