### ISSUE TITLE
Back : ศ.ตามแนวพระราชดำริฯ- หน้าบันทึกข้อมูล - เพิ่มปุ่มให้สามารถขยายการบันทึกรายละเอียด (กปร.ขอมา)

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#138]
![image](https://user-images.githubusercontent.com/31124544/33120517-dcef245c-cfa4-11e7-9132-2f470e70a197.png)

**Comment by RDPB2-Kuer** [comment]
ขอยกเลิกก่อน
