### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง- หน้าบันทึกข้อมูล - เพิ่มปุ่มให้สามารถขยายการบันทึกรายละเอียด (กปร.ขอมา)

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#139]
![image](https://user-images.githubusercontent.com/31124544/33120582-15b3a524-cfa5-11e7-8d05-c8fc6d2937ce.png)

**Comment by RDPB2-Kuer** [comment]
OK แต่จะขอหารือกับ กปร อีกครั้ง
