### ISSUE TITLE
Back :ศูนย์เรียนรู้อื่นๆ - หน้าจอบันทึกข้อมูลทั่วไป

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#14]
@cmmadnat  น้องแนต  รบกวนปรับตามรายละเอียดในภาพ 

![image](https://user-images.githubusercontent.com/31124544/32321647-5dc20c7c-bff4-11e7-8524-db16f80e82a0.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32487743-2306372e-c3dd-11e7-83a8-a83263c7a22b.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
