### ISSUE TITLE
Back : ศูนย์เรียนรู้อื่นๆ- หน้าบันทึกข้อมูล - เพิ่มปุ่มให้สามารถขยายการบันทึกรายละเอียด (กปร.ขอมา)

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#140]
![image](https://user-images.githubusercontent.com/31124544/33120679-70b0f29c-cfa5-11e7-8783-042318b62bea.png)

**Comment by RDPB2-Kuer** [comment]
ขอยกเลิกก่อน
