### ISSUE TITLE
Back : ศูนย์ศึกษาการพัฒนา ฯ หน้าแสดงรายการ ปุ่ม "ลบทิ้ง" ใช้งานไม่ได้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#144]
![image](https://user-images.githubusercontent.com/31124544/33121711-2ccb83aa-cfa8-11e7-9cfa-89fcfa2908b2.png)

**Comment by cmmadnat** [comment]
<img width="721" alt="screen shot 2560-11-24 at 16 31 29" src="https://user-images.githubusercontent.com/37333/33204096-f1c98598-d134-11e7-807a-01e2c4c1d493.png">

**Comment by Srikridsadaporn** [comment]
ยังใช้งานไม่ได้

**Comment by RDPB2-Kuer** [comment]
OK
