### ISSUE TITLE
Back : ศ.ตามแนวพระราชดำริฯ หน้าแสดงรายการ ปุ่ม "ลบทิ้ง" ใช้งานไม่ได้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#146]
![image](https://user-images.githubusercontent.com/31124544/33122877-1403fe80-cfab-11e7-8beb-ee22eff6e1c8.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-24 -3](https://user-images.githubusercontent.com/37333/33201068-a3405916-d129-11e7-8874-18b1777a22c1.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
