### ISSUE TITLE
Back : ศูนย์เรียนรู้อื่นๆ หน้าเพิ่มข้อมูล ตรวจสอบการบังคับเลือก จังหวัดและการแจ้งเตือนกรณีไม่เลือก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#147]
![image](https://user-images.githubusercontent.com/31124544/33156309-23dc87e8-d02b-11e7-8d63-b03766da3f21.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-24 -2](https://user-images.githubusercontent.com/37333/33200968-4a79f42c-d129-11e7-8f99-0e1a0ddae37b.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
