### ISSUE TITLE
Back : ศ.ตามแนวพระราชดำริฯหน้าเพิ่มข้อมูล การเลือก จังหวัดและการแจ้งเตือนกรณีไม่เลือก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#148]
![image](https://user-images.githubusercontent.com/31124544/33156784-9f97013e-d02f-11e7-8c4c-ed3db7f2fee7.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-24](https://user-images.githubusercontent.com/37333/33200850-e1bbd194-d128-11e7-9f69-2bf6c2c3ed4e.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-24 -1](https://user-images.githubusercontent.com/37333/33200925-24eb9e36-d129-11e7-925b-55ebf1b6b687.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
