### ISSUE TITLE
Back : ศ.อื่นๆ หน้าเพิ่มข้อมูล การเลือก จังหวัดและการแจ้งเตือนกรณีไม่เลือก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#149]
![image](https://user-images.githubusercontent.com/31124544/33156893-9fa7bdca-d030-11e7-87ca-4dd7765016a7.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-24 2](https://user-images.githubusercontent.com/37333/33200806-bc48aaf4-d128-11e7-9840-0fcfc24efb6a.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
