### ISSUE TITLE
Back :ศูนย์เรียนรู้อื่นๆ -หน้าจอบันทึกข้อมูลสถานที่ตั้ง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#15]
@cmmadnat  น้องแนต  รบกวนปรับตามรายละเอียดในภาพ 

![image](https://user-images.githubusercontent.com/31124544/32321685-85af4cfe-bff4-11e7-9c4b-bf76c5363715.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32487117-54a82582-c3db-11e7-8755-f0dc82cf79ba.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
