### ISSUE TITLE
Back : ศ.อื่นๆ หน้าแสดงรายการข้อมูล ปรับขนาดฟอนท์ส่วนการค้นหา

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#151]
น้องแนตคะ รบกวนปรับ (เคยแก้ไปแล้วทำไมวนกลับมาเหมือนเดิม)

![image](https://user-images.githubusercontent.com/31124544/33158514-1cede6ea-d03d-11e7-9104-0812b89b53cb.png)

**Comment by cmmadnat** [comment]
ขอกลับมาดูอีกครั้งภายหลังครับ

**Comment by RDPB2-Kuer** [comment]
OK
