### ISSUE TITLE
Back : ศูนย์เรียนรู้อื่นๆ หน้าแสดงรายการข้อมูล  ผลการค้นหาไม่ถูกต้อง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#152]
น้องแนตคะ
การค้นหา ศูนย์เรียนรู้อื่นๆ ผลการค้นหาไม่ตรงตามเงื่อนไข รายละเอียดดังนี้
ภาพ 1 รายการข้อมูลศูนย์เรียนรู้ทั้งหมด ในแถบสีแดงคือข้อมูลที่จะต้องแสดงเป็นผลเมื่อเลือกเงื่อนไข
ภาพ 2 แสดงเงื่อนไขการค้นหาข้อมูลด้วยการกำหนดเงื่อนไขเลือก หน่วยงาน "กอ.รมน.-กศน." ผลจากการค้นหาคือไม่มีข้อมูลแสดง ดังนั้นรบกวนตรวจสอบด้วยคะ

![image](https://user-images.githubusercontent.com/31124544/33158772-867666bc-d03f-11e7-9b1a-0d050b430f38.png)

![image](https://user-images.githubusercontent.com/31124544/33158834-03a443fc-d040-11e7-9e18-138f988356c6.png)

**Comment by RDPB2-Kuer** [comment]
OK
