### ISSUE TITLE
Back : ศูนย์เรียนรู้ตามแนวฯ  ปรับการแจ้งเตือน การบันทึกข้อมูลค่าพิกัดไม่ถูกต้อง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#154]
![image](https://user-images.githubusercontent.com/31124544/33162336-b6dce0c6-d05b-11e7-8d60-846c42f1c910.png)

**Comment by cmmadnat** [comment]
แก้พร้อม #156

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
