### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียงฯ ปรับการแจ้งเตือน การบันทึกข้อมูลค่าพิกัดไม่ถูกต้อง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#155]
![image](https://user-images.githubusercontent.com/31124544/33162503-5e4e4e26-d05c-11e7-9a90-20473ad85d82.png)

**Comment by cmmadnat** [comment]
แก้พร้อมกับ #156

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
