### ISSUE TITLE
Back : ศูนย์เรียนรู้อื่นๆ ปรับการแจ้งเตือน การบันทึกข้อมูลค่าพิกัดไม่ถูกต้อง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#156]
![image](https://user-images.githubusercontent.com/31124544/33162668-57b64d9c-d05d-11e7-813c-32e9e44bb667.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33193344-8f90e2c0-d0fa-11e7-8ea6-e27333768512.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
