### ISSUE TITLE
Back : หน้า DashBord ให้ระบบนับจำนวนศูนย์แต่ละประเภทในระบบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#159]
![image](https://user-images.githubusercontent.com/31124544/33237225-31b5e77a-d2a0-11e7-8144-3c65bf0ec56c.png)

**Comment by RDPB2-Kuer** [comment]
การคำนวนตัวเลขยังไม่ถูกต้อง

![image](https://user-images.githubusercontent.com/30930235/33253634-ee7d7450-d376-11e7-9b35-97b7282fc3ac.png)

**Comment by RDPB2-Kuer** [comment]
OK

**Comment by RDPB2-Kuer** [comment]
ข้อกราฟยังไม่ถูกต้อง
