### ISSUE TITLE
Back :ศูนย์เรียนรู้อื่นๆ -หน้าจอบันทึกข้อมูลการติดต่อ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#16]
@cmmadnat  น้องแนต  รบกวนปรับตามรายละเอียดในภาพ 

![image](https://user-images.githubusercontent.com/31124544/32321708-9d254a32-bff4-11e7-9c5c-ec7888d46dc5.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32487001-e9aa8644-c3da-11e7-889d-4ed4f4431594.png)

**Comment by Srikridsadaporn** [comment]
ปิด
