### ISSUE TITLE
Back : รายงานศูนย์เรียนรู้ - รบกวนดำเนินการด้วยค่ะ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#160]
รบกวนดำเนินการจัดทำรายงานศูนย์เรียนรู้ ตามรูปแบบไฟล์ที่แนบมาด้วย
[RDPB2-Report-V1.0.xlsx](https://github.com/cmmadnat/rdpb2/files/1503648/RDPB2-Report-V1.0.xlsx)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
