### ISSUE TITLE
Front :  ลงทะเบียนผู้ใช้งาน (สำหรับเจ้าหน้าที่) รบกวน linkกับหน้า Login ด้วย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#161]
![image](https://user-images.githubusercontent.com/31124544/33237285-a77d178e-d2a1-11e7-8e85-f1a3cd836bb6.png)

**Comment by cmmadnat** [comment]
แก้ link ไปยังศูนย์ศึกษาแล้วครับ

**Comment by RDPB2-Kuer** [comment]
ไม่ใช่นะคะ ให้ link ไปที่หน้า login คะ

**Comment by RDPB2-Kuer** [comment]
ทำไม่ได้นะคะ ดูขั้นตอนนี้

1. เรียก url ของ front อันเดียว คือ
![screen shot 2560-11-28 at 14 26 34](https://user-images.githubusercontent.com/30930235/33307400-ea69adde-d448-11e7-8b88-095f48bcad27.png)

2. เลือกลงทะเบียน ตามหน้านี้
![screen shot 2560-11-28 at 14 26 56](https://user-images.githubusercontent.com/30930235/33307304-9a18ecf0-d448-11e7-88af-dc9a5251ac9e.png)
 
3. ระบบยังไปที่ dashboard โดยไม่ผ่าน login
![screen shot 2560-11-28 at 14 27 01](https://user-images.githubusercontent.com/30930235/33307330-aebbd190-d448-11e7-8769-bab8d6b00fff.png)

**Comment by cmmadnat** [comment]
https://rdpb-2.appspot.com/logout
ล็อกเอาท์ก่อนครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
