### ISSUE TITLE
Back : ศ.ศึกษาการพัฒนา ตรวจสอบขั้นตอนการเตือนการบันทึกข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#165]
การตรวจสอบข้อมูลประกอบด้วย 

1. เมื่อกดบันทึก ตรวจสอบก่อนเลยว่า field ที่บังคับทุก field ใส่ข้อมูลครบแล้วหรือยัง
2. ถ้ายังใส่ไม่ครบก็แจ้งเตือนที่ใต้ field บังคับที่ไม่ได้ใส่ว่า “!บังคับใส่ข้อมูล”
3. ถ้าเป็น field ที่ต้องตรวจสอบข้อมูล แล้วใส่ข้อมูลไม่ถูกต้อง ก็ให้เแจ้งเตือนที่ใต้ field นั้นๆ ว่า “! ใส่ข้อมูลไม่ถูกต้อง”
4. ถ้าถูกต้องหมดแล้ว ก็ตรวจสอบว่า ชื่อกลุ่ม/ชุมชน ซ้ำหรือไม่ ถ้าซ้ำก็แจ้งเตือนว่า 
“! ข้อมูลซ้ำ”
5. ถ้าใส่ครบ ก็ตรวจสอบว่า field ที่ใส่บาง field ถูกต้องตามรูปแบบที่กำหนดไหม
***โดยการแจ้งเตือนใช้ default font และแสดงข้อความเตือนที่ใต้ input field แต่ละ field

**Comment by RDPB2-Kuer** [comment]
OK
