### ISSUE TITLE
Back :ศูนย์เรียนรู้อื่นๆ - หน้าจอบันทึกข้อมูลรูปภาพศูนย์เรียนรู้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#17]
@cmmadnat  น้องแนต  รบกวนปรับตามรายละเอียดในภาพ 

![image](https://user-images.githubusercontent.com/31124544/32321776-d5838560-bff4-11e7-9a49-0b34e648a488.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32486880-8fb8d992-c3da-11e7-8086-6d99e9e6b609.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
