### ISSUE TITLE
Front : ศ.พอเพียง - หน้าแสดงรายละเอียดศูนย์เรียนรู้ download เอกสาร

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#178]
![image](https://user-images.githubusercontent.com/31124544/33240654-36fb5a8e-d2ec-11e7-9ecc-137392ef36d5.png)

**Comment by cmmadnat** [comment]
ถ้ามีจะมีขึ้นครับ ไม่มีไฟล์ก็ไม่ขึ้น

**Comment by Srikridsadaporn** [comment]
Finished
