### ISSUE TITLE
Front  ศ.ตามแนว  หน้าแสดงรายละเอียดศูนย์เรียนรู้ download เอกสาร

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#179]
![image](https://user-images.githubusercontent.com/31124544/33240664-6bc0c5b0-d2ec-11e7-9e18-53cbc09bc06e.png)

**Comment by cmmadnat** [comment]
ถ้ามีจะมีขึ้นครับ ไม่มีไฟล์ก็ไม่ขึ้น

**Comment by Srikridsadaporn** [comment]
finished
