### ISSUE TITLE
Back :ศูนย์เรียนรู้อื่นๆ - หน้าจอบันทึกข้อมูลเอกสารประกอบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#18]
@cmmadnat  น้องแนต  รบกวนปรับตามรายละเอียดในภาพ 
![image](https://user-images.githubusercontent.com/31124544/32321822-0bc10120-bff5-11e7-9084-23708b5830a5.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32486858-795d2766-c3da-11e7-8ea4-f3ab8c1854bc.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
