### ISSUE TITLE
Front  ศ.อื่นๆ  หน้าแสดงรายละเอียดศูนย์เรียนรู้ download เอกสาร

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#180]
![image](https://user-images.githubusercontent.com/31124544/33240677-91569264-d2ec-11e7-8ddc-7960f0d063d4.png)

**Comment by cmmadnat** [comment]
ถ้ามีจะมีขึ้นครับ ไม่มีไฟล์ก็ไม่ขึ้น

**Comment by Srikridsadaporn** [comment]
finished
