### ISSUE TITLE
Back : ศ.พอเพียง - การแจ้งเตือนกรณีไม่ใส่ข้อมูลบังคับ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#187]
กรณีไม่ใส่ข้อมูลอะไรเลย แล้วกดปุ่ม "บันทึก" หรือ ใส่ข้อมูลบังคับไม่ครบ การแสดงผลข้อมูลไม่ถูกต้อง ให้ปรับแก้ ดังนี้

![image](https://user-images.githubusercontent.com/30930235/33249193-bb817ecc-d35b-11e7-963f-09526c6e05a0.png)

![image](https://user-images.githubusercontent.com/30930235/33249161-942968da-d35b-11e7-985e-d8220a4ce6b6.png)

และไม่ต้องแจ้งเรื่องข้อมูลซ้ำ เนื่องจากในขั้นตอนนี้ยังไม่ได้ติดต่อกับ DB จึงไม่ต้องแจ้งเตือนหน้านี้
![image](https://user-images.githubusercontent.com/30930235/33249344-9ffdc29a-d35c-11e7-8a0a-8c81ec0f1af7.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
