### ISSUE TITLE
Back : ศ.พอเพียง - ปุ่มลบข้อความที่บันทึกเองแสดง Icon ไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#189]
![image](https://user-images.githubusercontent.com/30930235/33249909-cd392b8e-d35f-11e7-94c5-2216de39756e.png)

**Comment by cmmadnat** [comment]
ยังเป็นอยู่ไหมครับ

**Comment by RDPB2-Kuer** [comment]
OK
