### ISSUE TITLE
Back :ศูนย์ศึกษาการพัฒนา ฯ- หน้าจอการแสดงรายการ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#19]
น้องแนต รบกวนปรับรายละเอียดตามภาพ

![image](https://user-images.githubusercontent.com/31124544/32322312-b1b9bb16-bff6-11e7-99d3-3d83f5321a40.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32486774-48bb638e-c3da-11e7-8e99-7b0b71ae38a2.png)

**Comment by Srikridsadaporn** [comment]
![image](https://user-images.githubusercontent.com/31124544/32639100-cde5ee14-c5f4-11e7-9732-c61448fa34fc.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อยคะ
