### ISSUE TITLE
Back : ศ.ศึกษา - การบันทึกรูปภาพ ปรับช่องชื่อ file และคำอธิบาย

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#191]
![image](https://user-images.githubusercontent.com/30930235/33252921-8a472e7a-d373-11e7-9306-21e4923bf1f3.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-9 2](https://user-images.githubusercontent.com/37333/33794207-00c3af9e-dcfa-11e7-8b4b-ca9570472b12.png)

**Comment by RDPB2-Kuer** [comment]
ยังไม่เห็นแก้เลยนิคะ แคบเหมือนเดิม
![image](https://user-images.githubusercontent.com/30930235/33874393-2e9964e6-df51-11e7-8ca4-73b056cb13f0.png)

**Comment by cmmadnat** [comment]
<img width="590" alt="screen shot 2560-12-13 at 13 12 04" src="https://user-images.githubusercontent.com/37333/33924135-3d13debe-e007-11e7-8659-d3dd352dab2e.png">

**Comment by RDPB2-Kuer** [comment]
OK
