### ISSUE TITLE
Back : ศ.ศึกษา - การบันทึกรูปภาพ ปรับปรุงการแสดงข้อความใต้ภาพ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#192]
![image](https://user-images.githubusercontent.com/30930235/33253042-337e0ac2-d374-11e7-9496-466128e92d4f.png)

**Comment by RDPB2-Kuer** [comment]
ปรับแก้ยังไม่ถูกต้องนะคะ
![image](https://user-images.githubusercontent.com/30930235/33306952-44fe25d8-d447-11e7-8a89-8f6f85596435.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-9 2 1](https://user-images.githubusercontent.com/37333/33794260-d34eee38-dcfa-11e7-972c-1935e595e49a.png)

**Comment by RDPB2-Kuer** [comment]
OK
