### ISSUE TITLE
Back : ศ.ตามแนว - การแจ้งข้อความเตือนกรณีไม่ใส่ข้อมูลบังคับ ยังไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#193]
เนื่องจากระบบแสดง Drop down list ของหัวข้อ "ประเภท" ด้วย ซึ่งไม่ถูกต้อง

**Comment by cmmadnat** [comment]
ต้องเขียนว่ายังไงครับ
<img width="398" alt="screen shot 2560-11-27 at 17 08 35" src="https://user-images.githubusercontent.com/37333/33261540-a5f6df9a-d395-11e7-94db-d71024ec93b4.png">

**Comment by RDPB2-Kuer** [comment]
OK
