### ISSUE TITLE
Front : ปรับขนาดของภาพและการแสดงข้อมูลแต่ละรายการ เท่ากัน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#196]
![image](https://user-images.githubusercontent.com/30930235/33296525-c03ba39e-d40e-11e7-9469-a263fa1c1d45.png)

**Comment by cmmadnat** [comment]
เป็นรูปแบบการแสดงผลครับ

**Comment by RDPB2-Kuer** [comment]
ไม่ใช่คะ คือ อยากให้ภาพ และการแสดงข้อมูลแต่ละภาพมีขนาดเท่ากันคะ

**Comment by RDPB2-Kuer** [comment]
เป็นแบบนี้ได้ไหมคะ
![image](https://user-images.githubusercontent.com/30930235/33429019-b4ab2770-d5fd-11e7-9dea-f0ac4772c095.png)

**Comment by RDPB2-Kuer** [comment]
ซ้ำกับ 260
