### ISSUE TITLE
Back : ศ. ตามแนว - ช่วยลดขนาด icon "!"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#198]
![image](https://user-images.githubusercontent.com/30930235/33296890-94b433f6-d410-11e7-8791-d4a667477c89.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33302420-7f985fc4-d42e-11e7-8c60-201104ecd213.png)

**Comment by RDPB2-Kuer** [comment]
OK
