### ISSUE TITLE
Web: Back Office การค้นหาศูนย์เรียนรู้อื่นๆ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#2]
การค้นหาศูนย์เรียนรู้อื่นๆ การแสดงผล ไม่ตรงตามเงื่อนไข
รายละเอียดตามภาพ
@cmmadnat 
![image](https://user-images.githubusercontent.com/31124544/32263361-26fba484-bf0c-11e7-9aa2-6e26bd485e13.png)

**Comment by cmmadnat** [comment]
กรณีเดียวกันครับ รบกวนทดสอบใหม่ครับ
อาจจะเป็นเพราะชื่อจังหวัดของการนำเข้าไม่ตรงกัน เมื่อนำเข้าแล้วจะทดสอบใหม่ครับ
<img width="1280" alt="screen shot 2560-11-02 at 15 12 27" src="https://user-images.githubusercontent.com/37333/32315812-483adbf4-bfe0-11e7-86aa-ce22559b3c45.png">
