### ISSUE TITLE
Back :ศูนย์ศึกษาการพัฒนา ฯ- หน้าจอการแสดงรายการ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#20]
@cmmadnat น้องแนต รบกวนปรับรายละเอียดตามภาพ
![image](https://user-images.githubusercontent.com/31124544/32322811-69441cee-bff8-11e7-9afa-e1cf513617b9.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32486756-3ce46dd0-c3da-11e7-9778-5775ff992ec7.png)

**Comment by Srikridsadaporn** [comment]
ซ้ำกับ #19 Closed 20
