### ISSUE TITLE
Back : การแสดง icon ลบข้อความแต่ละ field ให้แสดงเมื่อใส่ข้อมูล field นั้นๆ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#200]
![image](https://user-images.githubusercontent.com/30930235/33297530-1f772fae-d414-11e7-876f-a75006835cd5.png)

**Comment by cmmadnat** [comment]
หมายถึงตรงส่วนไหนเหรอครับ อันนี้ไม่ค่อยเข้าใจ

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/33302871-c6940dc6-d431-11e7-9ba2-5862b432daa4.png)

**Comment by cmmadnat** [comment]
ของผมไม่เป็นนะ
![image](https://user-images.githubusercontent.com/37333/33304963-631ade70-d43e-11e7-8796-3cc2958009ae.png)

**Comment by RDPB2-Kuer** [comment]
ของคุณก็เป็นไง ที่หัวข้อชื่อคน/ชื่อชุมชน  กับที่อยู่ศูนย์เรียนรู้ ไม่ได้ใส่ข้อมูลที่หัวข้อนั้นก็ไม่ควรแสดง icon นี้ออกมา มันเลอะเทอะค่ะ ให้แสดงที่หัวข้อที่กำลังใส่ข้อมูลที่อยู่ในกรอบสีฟ้าก็พอคะ

**Comment by RDPB2-Kuer** [comment]
มันเลอะเทอะแบบนี้
![image](https://user-images.githubusercontent.com/30930235/33312894-b2465656-d45b-11e7-813c-ef2d2ce3457d.png)
แบบนี้ดีกว่า
![image](https://user-images.githubusercontent.com/30930235/33313043-31e1ebdc-d45c-11e7-8133-4c422ac7e005.png)

**Comment by RDPB2-Kuer** [comment]
ตรวจสอบแล้วพบว่า บาง field ที่ต้องบันทึกเอง ยังไม่มี icon ลบข้อความขึ้นนะคะ ดังนี้

1. ศ. พอเพียง ได้แก่ หัวข้อ ถนน, รหัสไปรษณีย์, Lat, Long, โทรศัพท์, โทรสาร, Email, G-Chat, Line ID
2. ศ. ตามแนว ได้แก่ หัวข้อ หมู่บ้าน, ถนน
3. ศ. อื่นๆ ได้แก่ หัวข้อ รหัสไปรษณีย์, หมู่บ้าน, ถนน, Lat อื่นๆ, Long อื่นๆ, ผู้รับผิดชอบฯ, โทรศัพท์, โทรสาร, Email, G-Chat, Line ID, โทรสาร, Email, G-Chat, Line ID

**Comment by RDPB2-Kuer** [comment]
OK
