### ISSUE TITLE
Front : ศ. อื่นๆ - ที่หน้าแรก ขอปรับแก้ตำแหน่งการแสดงหัวข้อ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#206]
![image](https://user-images.githubusercontent.com/30930235/33299664-397b93d0-d41f-11e7-873e-c9ae94bfb061.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33300889-48213f56-d425-11e7-8f2f-fbd797c1d8ab.png)

**Comment by RDPB2-Kuer** [comment]
OK
