### ISSUE TITLE
Back :ศูนย์ศึกษาการพัฒนา ฯ - หน้าจอบันทึกข้อมูลทั่วไปและที่ตั้ง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#21]
น้องแนต รบกวนปรับรายละเอียดตามภาพ   @cmmadnat
![image](https://user-images.githubusercontent.com/31124544/32322878-9f619d10-bff8-11e7-9a4e-16f306b66203.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32486280-c6b061a6-c3d8-11e7-9f08-0659810b9355.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
