### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง   - ควบคุมไม่ให้ใส่  Video file ในหน้า“เอกสารประกอบ” 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#216]
![image](https://user-images.githubusercontent.com/31124544/33367196-493c8eee-d520-11e7-8ef6-6b556feec326.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33794780-32c8b498-dd05-11e7-9c93-e262998f1310.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
