### ISSUE TITLE
Back : ศ.ตามแนวฯ  - ควบคุมไม่ให้ใส่  Video file ในหน้า“เอกสารประกอบ” 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#217]
![image](https://user-images.githubusercontent.com/31124544/33367246-80b0c8b8-d520-11e7-8115-98210dbb7a41.png)

**Comment by cmmadnat** [comment]
fixed พร้อมกับ #216

**Comment by RDPB2-Kuer** [comment]
OK
