### ISSUE TITLE
Back : ศ.อื่นๆ - ควบคุมไม่ให้ใส่ Video file ในหน้า“เอกสารประกอบ”

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#218]
![image](https://user-images.githubusercontent.com/31124544/33367354-d394840c-d520-11e7-9da6-f1b87ae0c790.png)

**Comment by cmmadnat** [comment]
fixed พร้อมกับ #216

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
