### ISSUE TITLE
Front : ปรับปรุงภาพ Default ศูนย์เรียนรู้ใหม่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#219]
ขอให้ใช้ภาพจากน้องเล็กคะ

**Comment by cmmadnat** [comment]
<img width="744" alt="screen shot 2560-12-11 at 23 02 18" src="https://user-images.githubusercontent.com/37333/33840385-5f1bf884-dec7-11e7-93c3-cc1d564e7b70.png">

**Comment by RDPB2-Kuer** [comment]
OK
