### ISSUE TITLE
Back : ศูนย์ศึกษาการพัฒนา ฯ - หน้าจอบันทึกข้อมูลรูปภาพศูนย์เรียนรู้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#22]
น้องแนต รบกวนปรับรายละเอียดตามภาพ  @cmmadnat 
![image](https://user-images.githubusercontent.com/31124544/32322960-edaed6ea-bff8-11e7-977e-1cb62a1cd6bb.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32486124-4e71eeda-c3d8-11e7-9070-4f06bdcdaa3f.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ  น้องแนต
