### ISSUE TITLE
Back : ศ.ศึกษาการพัฒนา ฯ - ควบคุมไม่ให้ใส่ Video file ในหน้า“เอกสารประกอบ”

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#220]
![image](https://user-images.githubusercontent.com/31124544/33369680-f1a9d8d2-d527-11e7-9b67-af92017f690c.png)

**Comment by cmmadnat** [comment]
fixed พร้อมกับ #216

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
