### ISSUE TITLE
Back : ศ.อื่นๆ  -สำหรับ กอ.รมน. ขอเปลี่ยนสี Icon เป็นสีม่วง (ส่งสีตัวอย่างให้แล้ว

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#221]

**Comment by RDPB2-Kuer** [comment]
ขอมีช่องทางให้ กปร สามารถสร้างหน่วยงานใหม่ได้เอง และกำหนดสีประจำหน่วยงานนั้นด้วย

**Comment by Srikridsadaporn** [comment]
![image](https://user-images.githubusercontent.com/31124544/33409699-5633aa62-d5af-11e7-8f48-7a2600603d1a.png)

**Comment by RDPB2-Kuer** [comment]
OK
