### ISSUE TITLE
Back : ศ.อื่นๆ - ปรับแก้การใส่ข้อมูลเลขบัตรประชาชน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#226]
![image](https://user-images.githubusercontent.com/30930235/33371857-9ee22b98-d52e-11e7-9274-22a3636fdcd0.png)

**Comment by RDPB2-Kuer** [comment]
ไม่ถูกต้องคะ ขอให้แสดงข้อความดังนี้
![image](https://user-images.githubusercontent.com/30930235/33710722-160edd56-db74-11e7-8975-1eeeb18629d9.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-9 2 2](https://user-images.githubusercontent.com/37333/33795277-05145f82-dd11-11e7-9120-6b81c6b65de9.png)

**Comment by Srikridsadaporn** [comment]
![image](https://user-images.githubusercontent.com/31124544/33801450-09b49052-dd8e-11e7-8550-89d9ccd2551d.png)

**Comment by RDPB2-Kuer** [comment]
แนตคะ ช่วยดูก่อน พี่เขียนว่า บัตรประชาชน (* เฉพาะ กอ.รมน - กศน.) และ "*" เป็นสีแดง

**Comment by cmmadnat** [comment]
<img width="312" alt="screen shot 2560-12-11 at 22 40 25" src="https://user-images.githubusercontent.com/37333/33839258-4d098cea-dec4-11e7-995d-d779b43c1018.png">

**Comment by RDPB2-Kuer** [comment]
OK
