### ISSUE TITLE
Back : ศูนย์ศึกษาการพัฒนา ฯ - หน้าจอบันทึกข้อมูลเอกสารประกอบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#23]
น้องแนต รบกวนปรับรายละเอียดตามภาพ  @cmmadnat 
![image](https://user-images.githubusercontent.com/31124544/32323099-66894334-bff9-11e7-9224-a8d4e546aa16.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32485941-b899e6c4-c3d7-11e7-8552-b67afde03a00.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32486005-ec0ca0be-c3d7-11e7-9c8b-ca6e7d654869.png)

**Comment by Srikridsadaporn** [comment]
OK
