### ISSUE TITLE
Back : ศ.ตามแนว - เพิ่มปุ่ม "รายละเอียดเพิ่มเติม"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#236]
![image](https://user-images.githubusercontent.com/30930235/33409748-8a22c3b2-d5af-11e7-9800-a4c1337d58ac.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-7 2 2](https://user-images.githubusercontent.com/37333/33702992-9e5ff81e-db58-11e7-8c17-1272f3f77ba5.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
