### ISSUE TITLE
Back : ศ.อื่นๆ - เพิ่มปุ่ม "รายละเอียดเพิ่มเติม"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#237]
![image](https://user-images.githubusercontent.com/30930235/33409815-dee3db52-d5af-11e7-8aaa-e00529f0833f.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-7 2](https://user-images.githubusercontent.com/37333/33702360-ba9c8f72-db55-11e7-81f7-5a0177a546c7.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-7 2 1](https://user-images.githubusercontent.com/37333/33702370-c4467dd0-db55-11e7-8a93-e21109c38c7f.png)

**Comment by RDPB2-Kuer** [comment]
ขอให้ปรับการแสดงหน้าจอให้เหลือบรรทัดเดียว และขยายหน้าให้เต็มหน้าจอได้ไหมคะ และขอดูผลการทดสอบการแสดงรายละเอียดเพิ่มเติมบนหน้าจอ mobile เพื่อสรุปว่า จะรวมการบันทึกข้อมูลรายละเอียดเป็นหัวข้อเดียวดีกว่าไหม

**Comment by cmmadnat** [comment]
![screenshot-2017-12-9 2 3](https://user-images.githubusercontent.com/37333/33795392-0fab427e-dd13-11e7-87af-006b9cec657f.png)
ยังคงแบบเดิมไปก่อนนะครับ ไว้เดี๋ยวเจอกันค่อยตกลง ตอนนี้ขอขยายขนาดไว้ก่อน

**Comment by RDPB2-Kuer** [comment]
OK
