### ISSUE TITLE
Front : ศ.อื่นๆ - เพิ่มการแสดงข้อมูลรายละเอียดเพิ่มเติม

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#240]
ขอให้เพิ่มการแสดงข้อมูล field "รายละเอียดเพิ่มเติม" ต่อท้าย field ".... รายละเอียด" ไปเลย โดยไม่ต้องมีหัวข้อใหม่
![image](https://user-images.githubusercontent.com/30930235/33410235-e44a2e46-d5b1-11e7-91c9-3a47a4a1bdc4.png)

**Comment by RDPB2-Kuer** [comment]
ปรับแก้ให้เป็นแบบนี้
![image](https://user-images.githubusercontent.com/30930235/33830961-d55691fe-dea8-11e7-8181-cd691d5b11d1.png)

**Comment by cmmadnat** [comment]
<img width="1209" alt="screen shot 2560-12-11 at 23 40 40" src="https://user-images.githubusercontent.com/37333/33842298-b8b86134-decc-11e7-8e2d-a4311e19c06a.png">

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
