### ISSUE TITLE
Front : ศ. กอ.รมน.-กศน. (ศ.อื่นๆ) - เพิ่มปุ่ม "ที่ตั้งศ.บนแผนที่" และ "ภาพแผนที่ตั้งศ.

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#243]
รบกวนขอให้น้องเล็กช่วยออกแบบปุ่มที่แสดงตามภาพด้านล่างใหม่
โดยปุ่มที่ให้ออกแบบ (ทำเหมือน ITOK ก็ได้) ได้แก่

1.ที่ตั้งศูนย์เรียนรู้บนแผนที่
2. ภาพแผนที่ตั้งศูนย์เรียนรู้

![image](https://user-images.githubusercontent.com/31124544/33412359-5772ad3e-d5bd-11e7-8ace-fa0f55b6479a.png)

**Comment by RDPB2-Kuer** [comment]
OK
