### ISSUE TITLE
Front: ศ.อื่นๆ (กอ.รมน-กศน.) เปลี่ยนสี Header เป็นสีม่วงทุกที่

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#244]
![image](https://user-images.githubusercontent.com/31124544/33412681-9c3e5560-d5bf-11e7-9e20-1db0eb604e7f.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33795430-a3265476-dd13-11e7-8a99-d50a8e33bc60.png)
เปลี่ยนสำหรับหน้าแรกก่อน เดี๋ยวขอปรับเป็น design ใหม่ก่อนค่อยตรวจ front ส่วนของสีใหม่นะครับ

**Comment by Srikridsadaporn** [comment]
ค่ะ น้องแนต

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
