### ISSUE TITLE
Back : ขอเปลี่ยนปุ่ม logout

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#245]
![image](https://user-images.githubusercontent.com/30930235/33412842-97ffa872-d5c0-11e7-9b26-5cfb39a613da.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/33698316-3ff46fea-db3e-11e7-83bf-9916a2d22d42.png)

**Comment by cmmadnat** [comment]
อันนี้ผมไม่ค่อยเข้าใจว่าควรจะหน้าตาแบบไหนครับ

**Comment by Srikridsadaporn** [comment]
น้องแนต @cmmadnat  พี่กื้อคะ   @RDPB2-Kuer แบบโครงการใช้ได้ไหมค่ะ
![image](https://user-images.githubusercontent.com/31124544/33801243-75bcb2cc-dd87-11e7-9c0f-5db5dc383419.png)

**Comment by Srikridsadaporn** [comment]
Lock out แล้วไม่เข้าหน้า Front office หรือค่ะ

**Comment by RDPB2-Kuer** [comment]
เอาแบบนี้ดีกว่านะคะ คือ
1. ให้แสดงปุ่มตรงขวามือเหมือนที่ทำอยู่ แต่ให้มีกรอบสีเหลี่ยมเหมือน P1 และเมื่อ cursor อยู่ที่ปุ่มนี้ ให้แสดงค่า Logout ให้ด้วย
2. สำหรับปุ่มที่อยู่ใต้รูป จนท. ให้เอาออกคะ

**Comment by cmmadnat** [comment]
<img width="260" alt="screen shot 2560-12-13 at 13 10 51" src="https://user-images.githubusercontent.com/37333/33924106-14f06baa-e007-11e7-9772-6ede132c4d46.png">

**Comment by RDPB2-Kuer** [comment]
OK
