### ISSUE TITLE
Mobile : ปรับแก้ Service ชั่วคราว ให้ส่งข้อมูลรายละเอียดเพิ่มเติม เพื่อทดสอบการแสดงผล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#247]
ขอให้ปรับแก้ mobile service ชั่วคราว เพื่อลองทดสอบการแสดงข้อมูลรายละเอียดเพิ่มเติมของ ศ. พอเพียงบนหน้าจอ mobile 
![image](https://user-images.githubusercontent.com/31124544/33710612-bd9647ae-db73-11e7-9c54-ec979e36f4a1.png)

**Comment by cmmadnat** [comment]
เพิ่มให้แล้วครับ ส่วนที่สีแดงไว้คือข้อมูลที่เพิ่มขึ้นมา
![image](https://user-images.githubusercontent.com/37333/33795415-5b9a6c64-dd13-11e7-95e3-143048373342.png)

**Comment by RDPB2-Kuer** [comment]
OK
