### ISSUE TITLE
Web: Front Office ปรับหน้าการค้นหา"เพิ่มการค้นหา"

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#248]
น้องแนตคะ รบกวนปรับหน้าการค้นหารายละเอียดดังภาพ

ขอบคุณมากคะ

![image](https://user-images.githubusercontent.com/31124544/32030533-bea0db88-ba25-11e7-90d0-7253e9d3e665.png)

**Comment by cmmadnat** [comment]
แก้ไขเป็นหน้ารวม ค้นหาพระราชดำริ เป็นทั้งหมด 6 อย่างแทน

**Comment by cmmadnat** [comment]
<img width="1278" alt="screen shot 2560-12-08 at 15 26 49" src="https://user-images.githubusercontent.com/37333/33757334-4cf18496-dc2c-11e7-9697-eb783c739b42.png">

**Comment by RDPB2-Kuer** [comment]
OK
