### ISSUE TITLE
Back : ศ.อื่นๆ -สำหรับ กอ.รมน. ขอเปลี่ยนสี Icon เป็นสีม่วง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#249]
![image](https://user-images.githubusercontent.com/31124544/33758182-d5a1073c-dc2f-11e7-8806-008ab4b3569e.png)

**Comment by RDPB2-Kuer** [comment]
ยังเหมือนเดิมเลยคะ
![image](https://user-images.githubusercontent.com/30930235/33795240-55dcba28-dd10-11e7-8ecb-3917da25d0cc.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-9 2 4](https://user-images.githubusercontent.com/37333/33795406-2f13c780-dd13-11e7-8ef6-8ce71285697e.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
