### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอการแสดงรายการ Highlight เฉพาะ พื้นที่เป้าหมาย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#25]
น้องแนตค่ะ Highlight เฉพาะ พื้นที่เป้าหมายคะ ศูนย์เรียนรู้ ไม่ต้อง และช่วยปรับขนาดให้เท่ากันด้วยคะ
รายละเอียดตามภาพนะคะ

![image](https://user-images.githubusercontent.com/31124544/32429122-cc9cd50a-c2fb-11e7-8094-3978a126d699.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32485894-8cd70828-c3d7-11e7-9f8c-5a799c0bd71e.png)

**Comment by cmmadnat** [comment]
ถ้าไม่ highlight จะไม่เหมือนกัน ทำได้แค่ให้มันอยู่กันคนละสีครับ

**Comment by Srikridsadaporn** [comment]
ขอให้ไฮไลท์สถานะ "ศูนย์เรียนรู้" สีเดียวกับ สถานะข้อมูล "ครบถ้วน"

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
