### ISSUE TITLE
Back : ศ.อื่นๆ หน้าแสดงรายการศูนย์เรียนรู้ ดึงข้อมูลอื่นมาแสดงเป็นข้อมูลผู้รับผิดชอบศูนย์ (ตามภาพ)

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#250]
![image](https://user-images.githubusercontent.com/31124544/33801366-31d39cf6-dd8c-11e7-83bb-550e44617bf6.png)

**Comment by cmmadnat** [comment]
<img width="457" alt="screen shot 2560-12-11 at 23 39 11" src="https://user-images.githubusercontent.com/37333/33842228-87857e80-decc-11e7-9ce8-9df1a0f1eccc.png">
![Uploading Screen Shot 2560-12-11 at 23.39.18.png…]()

**Comment by cmmadnat** [comment]
<img width="451" alt="screen shot 2560-12-11 at 23 39 18" src="https://user-images.githubusercontent.com/37333/33842245-952d4374-decc-11e7-9beb-b9ee12d988f2.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
