### ISSUE TITLE
Front : หน้าแสดงรายละเอียดศูนย์เรียนรู้ ปุ่มลูกศรเลื่อนภาพยังใช้งานไม่ได้  และเพิ่มขนาดตัวอักษร

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#256]
![image](https://user-images.githubusercontent.com/31124544/33823719-a8faa22c-de8e-11e7-8580-50a4f463d7d3.png)

**Comment by cmmadnat** [comment]
ตัวอักษรขอปรึกษาก่อน แต่กดได้แล้วครับ

**Comment by RDPB2-Kuer** [comment]
OK
