### ISSUE TITLE
Front : หน้าแสดงข้อมูลศ.  ปรับขนาดรูปให้สมดุลกับพื้นที่

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#257]
![image](https://user-images.githubusercontent.com/31124544/33823977-736a69b6-de8f-11e7-9464-5cd1c27ea77c.png)

**Comment by cmmadnat** [comment]
<img width="1018" alt="screen shot 2560-12-11 at 23 28 59" src="https://user-images.githubusercontent.com/37333/33841737-1cc56c78-decb-11e7-93bc-bc10b18606ba.png">
ปรับให้อยู่กลางก่อนละกันครับ

**Comment by RDPB2-Kuer** [comment]
OK
