### ISSUE TITLE
Front : หน้าแสดงข้อมูล ศ. ขาดสัญลักษณ์ผู้ประสานงาน และชื่อผู้ประสานงาน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#259]
![image](https://user-images.githubusercontent.com/31124544/33825057-f735767a-de92-11e7-9b9e-dc1feddad122.png)

**Comment by cmmadnat** [comment]
<img width="637" alt="screen shot 2560-12-11 at 23 24 48" src="https://user-images.githubusercontent.com/37333/33841501-8160d8e4-deca-11e7-8c0a-e0ba0443c1b1.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
