### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอการแสดงรายการสถานะศูนย์เรียนรู้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#26]
รบกวนปรับแก้  ดังภาพนะคะ
![image](https://user-images.githubusercontent.com/31124544/32429745-97c25492-c2fe-11e7-87a9-b2dc643c91d1.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32485871-7783aaa8-c3d7-11e7-8376-5c7269e8fa8b.png)

**Comment by Srikridsadaporn** [comment]
น้องแนตคะ ปรับตามภาพ
![image](https://user-images.githubusercontent.com/31124544/32587816-24e99e76-c53d-11e7-9b96-59a76a741b14.png)
