### ISSUE TITLE
Front : หน้าแสดงรายการศูนย์เรียนรู้ ปรับแก้ให้ข้อมูลรายละเอียดแสดงไม่เกิน 8 บรรทัด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#260]
ต้องการให้ข้อมูล ศ. แต่ละแห่ง แสดงขนาดภาพเท่ากัน และจำนวนรายการเท่ากัน และมีข้อความ "อ่านต่อ+"  กรณีข้อมูลที่แสดงยังมีต่อด้วย
![image](https://user-images.githubusercontent.com/31124544/33825600-ba438a7a-de94-11e7-816e-eaac430dd5ca.png)

**Comment by cmmadnat** [comment]
<img width="598" alt="screen shot 2560-12-11 at 23 05 05" src="https://user-images.githubusercontent.com/37333/33840517-be9c3300-dec7-11e7-9a0b-f852071f2d59.png">

**Comment by RDPB2-Kuer** [comment]
ยังปรับแก้ไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/33864996-2bbd1634-df22-11e7-8272-000557913510.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
