### ISSUE TITLE
Back : ศ. อื่น ๆ หน้าเพิ่มข้อมูลศูนย์เรียนรู้  มีส่วนเกินเข้ามาดังภาพ รบกวนเอาออกด้วย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#261]
![image](https://user-images.githubusercontent.com/31124544/33825989-0456f89e-de96-11e7-9f93-3a71a774653c.png)

**Comment by cmmadnat** [comment]
<img width="1003" alt="screen shot 2560-12-11 at 22 32 36" src="https://user-images.githubusercontent.com/37333/33838898-598e3746-dec3-11e7-94ae-26b443720e82.png">
ส่วนของแผนที่ครับ

**Comment by RDPB2-Kuer** [comment]
OK
