### ISSUE TITLE
Back : ศ. ตามแนวฯ หน้าเพิ่มข้อมูลศูนย์เรียนรู้  มีส่วนเกินเข้ามาดังภาพ รบกวนเอาออกด้วย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#262]
![image](https://user-images.githubusercontent.com/31124544/33826042-3c14ad76-de96-11e7-9aec-6449fd1ae37e.png)

**Comment by cmmadnat** [comment]
<img width="1003" alt="screen shot 2560-12-11 at 22 32 36" src="https://user-images.githubusercontent.com/37333/33838849-3c30a92c-dec3-11e7-8686-92a3023d054d.png">
เป็นส่วนของแผนที่ครับ

**Comment by RDPB2-Kuer** [comment]
OK
