### ISSUE TITLE
Back : ศ. เศรษฐกิจพอเพียง หน้าเพิ่มข้อมูลศูนย์เรียนรู้  มีส่วนเกินเข้ามาดังภาพ รบกวนเอาออกด้วย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#263]
![image](https://user-images.githubusercontent.com/31124544/33826091-687db754-de96-11e7-9d49-c48be1c8957a.png)

**Comment by cmmadnat** [comment]
แก้ไขแล้วครับ เป็นส่วนของแผนที่ครับ

**Comment by cmmadnat** [comment]
![screenshot-2017-12-11 -2](https://user-images.githubusercontent.com/37333/33838681-c850732a-dec2-11e7-9e39-a1799e29aff7.png)

**Comment by RDPB2-Kuer** [comment]
OK
