### ISSUE TITLE
Back : ศ.อื่นๆ หน้าบันทึกข้อมูลศูนย์เรียนรู้ ไม่ "บันทึกข้อมูล" ที่มีการปรับเปลี่ยน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#264]
![image](https://user-images.githubusercontent.com/31124544/33827098-b5f351a8-de99-11e7-8336-073f86957df2.png)

**Comment by cmmadnat** [comment]
แก้ไขแล้วครับ

**Comment by RDPB2-Kuer** [comment]
ระบบยังแสดงไม่ถูกต้องเหมือนเดิม คือ เมื่อแก้ไขข้อมูลแล้วกดปุ่มบันทึก ระบบไม่แสดงข้อความว่า "บันทึกข้อมูลแล้ว" และเมื่อกลับมาดูข้อมูลใหม่ ข้อมูลที่แก้ไขก็ยังไม่ได้บันทึกค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
