### ISSUE TITLE
Back : ศ.อื่นๆ ข้อมูลตั้งต้นสำหรับการ convert ศูนย์เรียนรู้ กอ.รมน. - กศน. 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#265]
รบกวนปรับศูนย์เรียนรู้ กอ.รมน. - กศน.  ดังนี้
1. ปีจัดตั้งเป๊น "2558" ทั้งหมด
2.ด้าน/ประเภท/ชนิด คือ "ด้านความมั่นคงทั้งหมด"
หรือใช้ File ข้อมูลนี้ Dump ลงไปใหม่
[RDPB2-Conversion-Data-กอรมน-V3.1Resubmit.xlsx](https://github.com/cmmadnat/rdpb2/files/1547470/RDPB2-Conversion-Data-.-V3.1Resubmit.xlsx)

**Comment by RDPB2-Kuer** [comment]
ต้องรอ กอ.รมน. ปรับแก้ส่งมาให้ใหม่อีกครั้ง
