### ISSUE TITLE
Back : ศ.อื่นๆ หน้ารายการข้อมูลกับหน้ารายะเอียดไม่สอดคล้องกัน ตามภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#266]
![image](https://user-images.githubusercontent.com/31124544/33827536-4864c0ca-de9b-11e7-9d75-58b3455d1094.png)

**Comment by cmmadnat** [comment]
แก้ไขแล้วครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
