### ISSUE TITLE
Back : ศ.ตามแนว - ปรับแก้การแสดงตำแหน่ง รายละเอียดเพิ่มเติม

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#268]
![image](https://user-images.githubusercontent.com/30930235/33828915-99c1aab4-dea0-11e7-82aa-75e6e0b04559.png)
ให้เหมือนแบบบนี้
![image](https://user-images.githubusercontent.com/30930235/33828981-d70b0aaa-dea0-11e7-8162-a829e6d8e12c.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-11 -1](https://user-images.githubusercontent.com/37333/33837963-9dca1e5a-dec0-11e7-81c4-1fd48bb5ebc3.png)

**Comment by RDPB2-Kuer** [comment]
OK
