### ISSUE TITLE
Back : ศ.อื่นๆ - ปรับแก้การแสดงตำแหน่ง รายละเอียดเพิ่มเติม 

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#269]
![image](https://user-images.githubusercontent.com/30930235/33830127-7d025ce8-dea5-11e7-85b7-154011e499df.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-11](https://user-images.githubusercontent.com/37333/33837893-6de81764-dec0-11e7-8026-b098ccb70b65.png)

เข้าใจว่าหน้าตาแบบนี้ถูกไหมครับ

**Comment by RDPB2-Kuer** [comment]
OK
