### ISSUE TITLE
Back : เศรษฐกิจพอเพียง- หน้าแสดงรายการข้อมูล  ปรับขนาด Font ผู้ประสานงาน 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#27]
รบกวนปรับ ตามภาพ

![image](https://user-images.githubusercontent.com/31124544/32432470-56184b76-c30a-11e7-85dd-4389a12bc339.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32485758-16027c28-c3d7-11e7-9df3-b1f98dcde5a1.png)

**Comment by Srikridsadaporn** [comment]
ขนาดของ Font ที่บันทึกเองจะใหญ่กว่าที่เป็นตัวเลือก

![image](https://user-images.githubusercontent.com/31124544/32587640-1a95f86c-c53c-11e7-8a6d-58403916868a.png)

**Comment by Srikridsadaporn** [comment]
แก้ไขเรียบร้อยแล้ว
