### ISSUE TITLE
Front : ศ.พอเพียง - กดข้อความผิดแล้วเกิด error

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#270]
![image](https://user-images.githubusercontent.com/30930235/33830420-ae5acf2c-dea6-11e7-9fdc-9d80d9cbf592.png)
เกิด error แบบนี้
![image](https://user-images.githubusercontent.com/30930235/33830471-de1d359c-dea6-11e7-951d-97d06e432571.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
