### ISSUE TITLE
Back : ศ.อื่นๆ - หลังหัวข้อพิกัด มีช่องเว้นว่างมากเกินไป

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#271]
![image](https://user-images.githubusercontent.com/30930235/33831815-29377cae-deac-11e7-99eb-9863482e8fed.png)

**Comment by cmmadnat** [comment]
แผนที่บน server ไม่ขึ้น กำลังดูอยู่ครับ

**Comment by cmmadnat** [comment]
![Uploading Screenshot-2017-12-11 โครงการระบบภูมิสารสนเทศโครงการอันเนื่องมาจากพระราชดำริและศูนย์เรียนรู้ (ระยะที่ 2).png…]()

**Comment by RDPB2-Kuer** [comment]
OK
