### ISSUE TITLE
Front : หน้าแสดงรายละเอียดศ. เมื่อเลือกกดปุ่ม เพื่อดูเอกสารเพิ่มเติมเกิด Error ดังภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#272]
![image](https://user-images.githubusercontent.com/31124544/33833768-482730da-deb3-11e7-8b1b-b5b6bb74bc9a.png)

**Comment by RDPB2-Kuer** [comment]
OK
