### ISSUE TITLE
Front : ศ.อื่นๆ  หน้าแสดงรายละเอียดศูนย์  ข้อมูลผู้ประสานงานแสดงไม่ครบตามที่มีใน Back

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#275]
![image](https://user-images.githubusercontent.com/31124544/33860987-ebaba39e-df0d-11e7-9138-15e5034e5a7f.png)

**Comment by RDPB2-Kuer** [comment]
ข้อมูลผู้ประสานงานและผู้รับผิดชอบแสดงผลข้อมูล สลับกัน

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
