### ISSUE TITLE
Front : ศ.พอเพียง - ปรับปรุงหน้าแสดงรายละเอียดข้างภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#278]
![image](https://user-images.githubusercontent.com/31124544/33871227-2d14e1c0-df44-11e7-8800-5a8300cdc62b.png)

มีเพิ่มเติมอีก โดยเป็นการแสดงข้อมูลครบทุก field
![image](https://user-images.githubusercontent.com/30930235/33918603-e5358b36-dfe6-11e7-943a-fde12091fcc3.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
