### ISSUE TITLE
Front : ศ.พอเพียง - ไม่แสดงข้อมูลโทรสาร และปรับแก้การแสดงข้อมูลที่อยู่

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#279]
![image](https://user-images.githubusercontent.com/31124544/33872249-a626e87a-df48-11e7-980b-47faf6635234.png)

และมีส่วนเพิ่มเติม ดังนี้
![image](https://user-images.githubusercontent.com/30930235/33916057-7afa4098-dfd9-11e7-9507-64f710ba135e.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
