### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอบันทึกข้อมูลศูนย์เรียนรู้ ปรับFont

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#28]
น้องแนตคะ รบกวนปรับตามภาพค่ะ

![image](https://user-images.githubusercontent.com/31124544/32433746-9b120ef2-c30e-11e7-9387-792225f1945e.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32485736-02a81f66-c3d7-11e7-8d52-738385397ead.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
