### ISSUE TITLE
Front : ศ.พอเพียง ปรับปรุงการแสดงรายละเอียดใต้ภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#280]
![image](https://user-images.githubusercontent.com/30930235/33918345-55179a5e-dfe5-11e7-9f16-f44dcff14bc9.png)

รูปแบบข้อมูลที่บันทึก คือ
![image](https://user-images.githubusercontent.com/30930235/33918897-7dd8d414-dfe8-11e7-89d4-596599d8f891.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
