### ISSUE TITLE
Back : ทุก ศ. - หน้ารูปภาพศูนย์เรียนรู้ ปรับขนาดภาพให้เท่ากัน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#286]
![image](https://user-images.githubusercontent.com/31124544/33877200-3e6f6f10-df5a-11e7-894e-650a56dffce4.png)

**Comment by cmmadnat** [comment]
ลดขนาดรูปและให้อยู่ตรงกลางแทนนะครับ

**Comment by cmmadnat** [comment]
<img width="588" alt="screen shot 2560-12-13 at 11 56 41" src="https://user-images.githubusercontent.com/37333/33922348-b5001574-dffc-11e7-850e-b33702fe09a4.png">

**Comment by RDPB2-Kuer** [comment]
OK
