### ISSUE TITLE
Back : ศ.ศึกษา - หน้าบันทึกข้อมูล ปุ่มด้านบนหายเมื่อไป Tab รูปภาพ หรือเอกสาร

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#287]
หน้าบันทึกข้อมูลศูนย์เรียนรู้ ปุ่มสี่ปุ่มด้านบนหายเมื่อไป Tab รูปภาพ

![image](https://user-images.githubusercontent.com/31124544/33877487-1784f4a0-df5b-11e7-8a07-444fe84d9597.png)

**Comment by RDPB2-Kuer** [comment]
OK
