### ISSUE TITLE
Back : ทุก ศ. - หน้าเอกสารประกอบ ปรับขนาดเอกสารทุกอันให้เท่ากัน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#288]
![image](https://user-images.githubusercontent.com/31124544/33877619-8932f6e2-df5b-11e7-92b3-a2576a077bfd.png)

**Comment by cmmadnat** [comment]
<img width="451" alt="screen shot 2560-12-13 at 11 46 37" src="https://user-images.githubusercontent.com/37333/33922151-50567268-dffb-11e7-829e-1fa07e8b6d8c.png">

**Comment by RDPB2-Kuer** [comment]
OK
