### ISSUE TITLE
Back : ทุกศ. - ในกรณีบันทึกข้อมูลบังคับไม่ครบให้แจ้ง error message ด้วย

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#289]
ขอให้ระบบแสดงผลในกรณีที่พบว่าบันทึกข้อมูลบังคับไม่ครบ โดยให้แสดง error message ว่า 
"บันทึกข้อมูลบังคับไม่ครบ" สักระยะหนึ่ง แล้วหายไปโดยอัตโนมัติ

**Comment by cmmadnat** [comment]
เหมือนตอนแรกบอกว่าไม่ต้องมี ขึ้นแค่ข้างใต้ข้อความของแต่ละช่องก็พอ

**Comment by RDPB2-Kuer** [comment]
OK
