### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง-กำหนดค่าข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#29]
น้องแนตคะ ปรับตามภาพด้วยนะคะ
![image](https://user-images.githubusercontent.com/31124544/32434542-fa16fe24-c310-11e7-8944-6f854939c199.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32485683-e1980c64-c3d6-11e7-8590-9f2087578af1.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
