### ISSUE TITLE
Front : ศ.ตามแนว - ปรับปรุงหน้าแสดงรายละเอียดข้างภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#290]
![image](https://user-images.githubusercontent.com/31124544/33879844-39d02582-df62-11e7-9bef-57c582babe74.png)

ปรับตรงนี้ด้วยคะ
![image](https://user-images.githubusercontent.com/30930235/34070924-62d24ff0-e2a0-11e7-8fb3-e327a42dfdc1.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
