### ISSUE TITLE
Icon ศ.อื่นๆ ให้เป็นสีน้ำเงินกรมท่า

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#293]
ขอเปลี่ยนจากเดิมที่เป็นสีแดง เป็นสีน้ำเงินกรมท่า

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/33994652-f3722592-e10d-11e7-9479-a171ff0183f5.png)

![image](https://user-images.githubusercontent.com/30930235/33994719-3853b7e8-e10e-11e7-9879-36a859849ba3.png)

**Comment by cmmadnat** [comment]
<img width="492" alt="screen shot 2560-12-15 at 11 36 55" src="https://user-images.githubusercontent.com/37333/34026974-4591d25e-e18c-11e7-9fcd-619f39752372.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
