### ISSUE TITLE
Back : ศ.อื่นๆ - เพิ่มข้อมูลตัวเลือกที่หัวข้อ ด้าน/ประเภท/ชนิด

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#298]
ขอให้เพิ่มตัวเลือก "เกษตรผสมผสาน" ที่หัวข้อ ด้าน/ประเภท/ชนิด

**Comment by cmmadnat** [comment]
<img width="706" alt="screen shot 2560-12-13 at 11 11 55" src="https://user-images.githubusercontent.com/37333/33921465-8346b598-dff6-11e7-8a04-4eb81a915e05.png">

**Comment by RDPB2-Kuer** [comment]
OK
