### ISSUE TITLE
Back : ทุกศ. - หน้าบันทึกข้อมูล Tab สถานที่ตั้ง ปรับตำแหน่งรูปแผนที่ และขยายขนาดแผนที่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#299]
![image](https://user-images.githubusercontent.com/30930235/33884636-06c6ac86-df73-11e7-97cf-0c45c8436c92.png)

**Comment by cmmadnat** [comment]
<img width="981" alt="screen shot 2560-12-18 at 15 32 24" src="https://user-images.githubusercontent.com/37333/34096644-ae13629c-e408-11e7-8971-2cb1f5bbbe37.png">

**Comment by Srikridsadaporn** [comment]
น้องแนตค่ะ แก้ด่วน ศ.ตามแนวพระราชดำริ กลายเป็นตามภาพด้านล่างไปแล้ว

![image](https://user-images.githubusercontent.com/31124544/34137253-748e925a-e49c-11e7-827f-d1cbe4b7e9d6.png)

**Comment by RDPB2-Kuer** [comment]
OK
