### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอการแสดงรายการ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#3]
น้องแนตคะ รบกวนปรับรายละอียดตามภาพ
1
 ![image](https://user-images.githubusercontent.com/31124544/32315563-2bf166f8-bfdf-11e7-9c7d-e56fbb7db047.png)

**Comment by cmmadnat** [comment]
ข้อ 1 แก้ไขแล้ว แต่ส่วนของการแสดงผลในช่องของพื้นที่เป้าหมายกับศูนย์ จะแยกเป็นคนละสีตามสถานะครับ

**Comment by RDPB2-Kuer** [comment]
ขอปรับแก้เพิ่มหน่อย สำหรับข้อ 1 และขอเพิ่มเติมส่วนของ Icon ด้วยคะ

![image](https://user-images.githubusercontent.com/30930235/32318131-d48823f2-bfe8-11e7-9baa-7864760d8438.png)

**Comment by RDPB2-Kuer** [comment]
ขอให้ปรับปรุงเพิ่มเติม ตามแนบ
![image](https://user-images.githubusercontent.com/30930235/32359424-95c4fc1a-c080-11e7-99e6-30dcd7b06c7b.png)

**Comment by RDPB2-Kuer** [comment]
รบกวนขอแสดงหัวข้อการแสดงผลข้อมูล ที่ปรับปรุงใหม่ ดังแนบ
โดยจะมีผลสำหรับทุกศูนย์เรียนรู้เลย

![image](https://user-images.githubusercontent.com/30930235/32359592-b345202a-c081-11e7-9cac-d54b55053b51.png)

**Comment by cmmadnat** [comment]
แก้ไขขนาด และคำพูดในหน้าแรก ถัดไป ในทุกหน้าแล้วครับ
![image](https://user-images.githubusercontent.com/37333/32360990-eb259f0e-c08d-11e7-88f9-c4b0eb1c6f85.png)

**Comment by RDPB2-Kuer** [comment]
1. ข้อ 2, 3, 4 ยังไม่ถูกต้องนะคะ
2. ตรงสถานะศูนย์เรียนรู้ ไม่ต้องมี Hightlight จะมี Higlight สีเขียว กรณีเป็น พื้นที่เป้าหมาย
3. หัวข้อ ด้าน/ประเภท/ชนิด ต้องกว้างกว่านี้ะ สามารถลดขนาด วันที่เปลี่ยนแปลงล่าสุดได้

**Comment by RDPB2-Kuer** [comment]
ขอปรับปรุงเพิ่มเติม ดังนี้
![image](https://user-images.githubusercontent.com/30930235/32362589-2e100246-c09d-11e7-9afc-b09e4fd75fe4.png)

**Comment by cmmadnat** [comment]
แก้ไขเรื่องของปุ่ม และคำว่าหน้าสุดท้าย และปุ่มให้แล้วครับ
แต่ ไฮไลต์ต้องมีของศูนย์เรียนรู้ แต่สำหรับพื้นที่เป้าหมายจะเป็นคนละสีกันครับ
<img width="1280" alt="screen shot 2560-11-03 at 16 21 31" src="https://user-images.githubusercontent.com/37333/32366995-172eee82-c0b3-11e7-8643-3da580264f72.png">

**Comment by RDPB2-Kuer** [comment]
ตามที่น้องออกแบบ คือ
Highlight เฉพาะ พื้นที่เป้าหมายคะ ศูนย์เรียนรู้ ไม่ต้อง และช่วยปรับขนาดให้เท่ากันด้วยคะ
![image](https://user-images.githubusercontent.com/30930235/32373091-1d25b35e-c0ca-11e7-8875-8d000567e96d.png)

**Comment by RDPB2-Kuer** [comment]
ปรับแก้ ดังนี้
![image](https://user-images.githubusercontent.com/30930235/32373245-ec3d62a4-c0ca-11e7-88f2-2d53c8b5bfbd.png)

**Comment by Srikridsadaporn** [comment]
ปรับเป็นข้อย่อยแล้ว...ขอ Closed ค่ะ
