### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอบันทึกข้อมูล ย่อ-ขยาย TAB

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#30]
น้องแนตคะ ปรับให้ย่อเก็บ หรือขยายให้ใหญ่เพื่อเพิ่มพื้นที่ทำงาน ด้วยนะคะ

![image](https://user-images.githubusercontent.com/31124544/32434691-6e632a78-c311-11e7-8392-92972ba34834.png)

**Comment by cmmadnat** [comment]
แก้ไขแล้วครับ

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ

**Comment by RDPB2-Kuer** [comment]
ยังไม่ถูกต้อง ดังนี้

![image](https://user-images.githubusercontent.com/30930235/32485580-8720c64a-c3d6-11e7-82a4-bd88ae7f9325.png)

**Comment by Srikridsadaporn** [comment]
น้องแนตคะ อย่าลืมเปลี่ยนลูกศรด้วย ตามรายละเอียดด้านบน

**Comment by Srikridsadaporn** [comment]
ปรับแก้เรียบร้อยแล้ว

![image](https://user-images.githubusercontent.com/31124544/32821565-a1333942-ca06-11e7-8624-7749a6005150.png)
