### ISSUE TITLE
Back : ทุกศ. - ขอเพิ่ม Font ในการใส่ข้อมูลรายละเอียดเพิ่มเติม

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#301]
ขอให้ปรับขนาด font ได้ด้วย
![image](https://user-images.githubusercontent.com/30930235/33918035-f2d0aa4e-dfe3-11e7-8d71-c2b9fc400b66.png)

**Comment by cmmadnat** [comment]
<img width="459" alt="screen shot 2560-12-18 at 15 27 20" src="https://user-images.githubusercontent.com/37333/34096462-f7f958ea-e407-11e7-83dc-8a4684d15b65.png">
เอาที่ให้เลือก font ออก

**Comment by RDPB2-Kuer** [comment]
OK
