### ISSUE TITLE
Front : ศ.ตามแนว หน้ารายละเอียดศูนย์เรียนรู้ - ปรับปรุงปุ่ม "การนำทางบนแผนที่" ในกรณีไม่มีค่าพิกัด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#302]
ปรับปรุงปุ่ม "การนำทางบนแผนที่" ในกรณีไม่มีค่าพิกัด ด้วยการไม่สามารถใช้งานได้ และยังคงแสดงหน้ารายละเอียดศูนย์เรียนรู้

**Comment by RDPB2-Kuer** [comment]
OK
