### ISSUE TITLE
Front : ศ.พอเพียง หน้าผลลัพธ์การค้นหา ปรับปรุงการแสดงผล กรณีไม่มีภาพ 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#305]
![image](https://user-images.githubusercontent.com/31124544/33919405-2165a65a-dfeb-11e7-91f4-e6311f6297dc.png)

**Comment by cmmadnat** [comment]
ตาม #305

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
