### ISSUE TITLE
Front : ศ.ตามแนว  หน้าผลลัพธ์การค้นหา - ปรับปรุงการแสดงผล กรณีไม่มีภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#306]
![image](https://user-images.githubusercontent.com/31124544/33919928-d283322a-dfed-11e7-8e04-a9ba54cbcf2e.png)

**Comment by cmmadnat** [comment]
ตาม #307

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
