### ISSUE TITLE
Front : ศ.อื่นๆ  หน้าผลลัพธ์การค้นหา - ปรับปรุงการแสดงผล กรณีไม่มีภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#307]
![image](https://user-images.githubusercontent.com/31124544/33920197-3b69e2c4-dfef-11e7-87bf-13a238f7fb48.png)

**Comment by cmmadnat** [comment]
<img width="419" alt="screen shot 2560-12-15 at 16 49 17" src="https://user-images.githubusercontent.com/37333/34036487-eba1e4b0-e1b7-11e7-8483-ffac1095c6b7.png">
เอาด้านบนไว้ไหมครับ จะได้เหมือนกับของโครงการ พระราชดำริ และองค์ความรู้

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
