### ISSUE TITLE
Back : ศ.อื่นๆ - เพิ่มข้อมูลตัวเลือกที่หัวข้อ "หน่วยงาน"

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#308]
ขอให้เพิ่มตัวเลือกในหัวข้อ "หน่วยงาน"อีก 3 หน่วยงานคือ 1) ธกส.  2) ศปร.  และ 3) สปก."

**Comment by cmmadnat** [comment]
<img width="220" alt="screen shot 2560-12-13 at 16 19 36" src="https://user-images.githubusercontent.com/37333/33931038-72bee51c-e021-11e7-8112-fe13e36980ba.png">

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/33994792-7a38a61e-e10e-11e7-9ad6-860b8f87fe06.png)

**Comment by cmmadnat** [comment]
<img width="1252" alt="screen shot 2560-12-15 at 11 34 42" src="https://user-images.githubusercontent.com/37333/34026928-f92f2baa-e18b-11e7-9be7-70d265b669b7.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
