### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอรายการ ปรับแก้การแสดงข้อมูลชื่อคน/ชุมชน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#31]
น้องแนตคะ ปรับด้วยคะ

![image](https://user-images.githubusercontent.com/31124544/32486829-6776f324-c3da-11e7-80b4-06f803a8a7a3.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
