### ISSUE TITLE
Front : ศ.อื่นๆ หน้าแสดงรายละเอียด ศ. เพิ่มการแสดงพิกัดอื่นๆ ที่เกี่ยวข้องด้วย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#314]
![image](https://user-images.githubusercontent.com/31124544/33980764-dbabb418-e0dc-11e7-99c8-fbf915fe5918.png)

**Comment by cmmadnat** [comment]
<img width="479" alt="screen shot 2560-12-15 at 16 39 03" src="https://user-images.githubusercontent.com/37333/34036019-7d216048-e1b6-11e7-9f65-2452c4fd49fe.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
