### ISSUE TITLE
Front : หน้าแรก/ ศ.พอเพียง เพิ่มชื่อจังหวัดหลังชื่อศูนย์และเอา " | o " ออก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#316]
![image](https://user-images.githubusercontent.com/31124544/33981959-6726ad1e-e0e1-11e7-8b25-589adc68f2a3.png)

**Comment by cmmadnat** [comment]
ตาม #318

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
