### ISSUE TITLE
Front : หน้าแรก/ ศ.ตามแนว เพิ่มชื่อจังหวัดหลังชื่อศูนย์และเอา " | o " ออก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#317]
![image](https://user-images.githubusercontent.com/31124544/33982232-5f5d33d6-e0e2-11e7-9d98-2b0b0e4a44ff.png)

**Comment by cmmadnat** [comment]
ตาม #318

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
