### ISSUE TITLE
Front : หน้าแรก/ ศ.อื่น เพิ่มชื่อจังหวัดหลังชื่อศูนย์และเอา " | o " ออก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#318]
![image](https://user-images.githubusercontent.com/31124544/33982347-c1257f92-e0e2-11e7-9c8c-0101739f388b.png)

**Comment by cmmadnat** [comment]
แก้เป็นชื่อจังหวัดแทนครับ

**Comment by RDPB2-Kuer** [comment]
OK
