### ISSUE TITLE
ฺBack : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอบันทึกข้อมูล ปรับแก้ค่า Default ค่าสถานะข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#32]
น้องแนตคะ รบกวนปรับตามภาพ
![image](https://user-images.githubusercontent.com/31124544/32591927-0e22c1ce-c554-11e7-9455-84c0c94826b7.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
