### ISSUE TITLE
Front : หน้าแสดงรายละเอียดข้อมูล ศ.  - พิกัดอื่นๆที่เกี่ยวข้องใช้งานไม่ได้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#321]
![image](https://user-images.githubusercontent.com/31124544/34067755-3677eb5c-e261-11e7-8c86-c9071763a742.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
