### ISSUE TITLE
Front : ศ.อื่นๆ : ปรับแก้หน้าจอแสดงรายละเอียดใหม่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#322]
![image](https://user-images.githubusercontent.com/30930235/34071171-f55f4d06-e2a4-11e7-89c0-0a67f1dffccc.png)

**Comment by cmmadnat** [comment]
<img width="608" alt="screen shot 2560-12-18 at 13 21 52" src="https://user-images.githubusercontent.com/37333/34092519-6f430f3e-e3f6-11e7-9719-a65f78415704.png">

**Comment by cmmadnat** [comment]
<img width="776" alt="screen shot 2560-12-18 at 13 24 27" src="https://user-images.githubusercontent.com/37333/34092597-d0cfa9a6-e3f6-11e7-9476-160ac35e91c3.png">

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
