### ISSUE TITLE
Front : ศ.พอเพียง - ปรับแก้การแสดงรายละเอียดใหม่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#325]
ในส่วนของรายละเอียดให้แสดงตามบรรทัดที่ user ใส่มา ไม่ใช่มารวมเป็นบรรทัดเดียวกัน

![image](https://user-images.githubusercontent.com/30930235/34071395-4ce88382-e2a8-11e7-996f-02229dc4174d.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-18](https://user-images.githubusercontent.com/37333/34092328-72590fda-e3f5-11e7-8cdf-5c87f3622abb.jpg)

**Comment by RDPB2-Kuer** [comment]
OK
