### ISSUE TITLE
Front : ศ.ตามแนว - ปรับแก้การแสดงรายละเอียดใหม่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#326]
![image](https://user-images.githubusercontent.com/30930235/34071582-9ffa36c2-e2aa-11e7-8ca1-7aa61eddc336.png)

**Comment by cmmadnat** [comment]
<img width="1213" alt="screen shot 2560-12-18 at 11 48 22" src="https://user-images.githubusercontent.com/37333/34090420-63e12a66-e3e9-11e7-97cd-b45e83b1710a.png">

**Comment by RDPB2-Kuer** [comment]
OK
