### ISSUE TITLE
Front : ทุกศ.​- ขอคำแนะนำกรณีแสดงปุ่ม ดูที่ตั้ง และ นำทาง 

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#327]
1. ในกรณีที่ไม่มีภาพแผนที่ตั้ง หรือนำทางบนแผนที่ ให้แสดงรูป Icon เป็นสีจาง ได้ไหมคะ
![image](https://user-images.githubusercontent.com/30930235/34071648-ca07d2ac-e2ab-11e7-8803-8e7addeee792.png)

2. ศ.อื่นๆ ไม่ต้องมีปุ่มสำหรับนำทางบนแผนที่พิกัดอื่นๆ แต่จะแสดงพิกัดอื่นๆ พร้อมกับการแสดงพิกัดศ. ได้ไหมคะ

**Comment by cmmadnat** [comment]
ข้อ 2 ไม่ได้ครับ

**Comment by cmmadnat** [comment]
<img width="555" alt="screen shot 2560-12-18 at 11 29 50" src="https://user-images.githubusercontent.com/37333/34090032-cb11ea7a-e3e6-11e7-8ffe-91f51db3a42c.png">

**Comment by RDPB2-Kuer** [comment]
OK
