### ISSUE TITLE
Front : ศ.พอเพียง   หน้าแรก และหน้าแสดงรายการศ. ตัดการแสดงพื้นที่ิเป้าหมายออก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#328]
![image](https://user-images.githubusercontent.com/31124544/34097093-62aba696-e40a-11e7-9e01-6ac1eb6d5b5e.png)

**Comment by RDPB2-Kuer** [comment]
OK
