### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง-ข้อมูลทั่วไป

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#33]
น้องแนตคะ รบกวนปรับตามภาพคะ

![image](https://user-images.githubusercontent.com/31124544/32584965-9c33d5d8-c52d-11e7-8a11-2284c89b22bd.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
