### ISSUE TITLE
Front : ศ. ตามแนว หน้ารายละเอียดศ. ตัดหัวข้อรางวัลออก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#330]
![image](https://user-images.githubusercontent.com/31124544/34098700-d6a76bac-e40f-11e7-9fe4-d1adc3707a97.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-20](https://user-images.githubusercontent.com/37333/34192668-02e8abc2-e582-11e7-9065-813ad1e6dbeb.png)

**Comment by RDPB2-Kuer** [comment]
OK
