### ISSUE TITLE
Front : ศ.พอเพียง - รายละเอียดไม่แสดงข้อมูลโทรสาร

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#333]
ใน Back office มีข้อมูลโทรสาร
![image](https://user-images.githubusercontent.com/30930235/34139761-1c2a5056-e4a9-11e7-8cd8-f0a2c1d890b3.png)

แต่ใน Front ข้อมูลโทรสาร ไม่แสดง
![image](https://user-images.githubusercontent.com/30930235/34139784-3d292d4a-e4a9-11e7-9294-2533c5ef3ee9.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/34141655-2ab81548-e4b5-11e7-828e-aa013591f6f6.png)

**Comment by RDPB2-Kuer** [comment]
OK
