### ISSUE TITLE
Front : ทุก ศ. - ปรับ font การแสดงข้อมูลให้เท่ากัน (หลายครั้งแล้ว)

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#335]
![image](https://user-images.githubusercontent.com/30930235/34143473-74873776-e4bf-11e7-9707-dbbb9c4f2671.png)

**Comment by cmmadnat** [comment]
ปรับเป็น 15px หมดแล้วครับ

**Comment by RDPB2-Kuer** [comment]
OK
