### ISSUE TITLE
Front : ศ. อื่นๆ - รายละเอียดศูนย์ ขอให้ปรับขนาด font ให้เท่ากัน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#336]
![image](https://user-images.githubusercontent.com/30930235/34158429-fc95dc02-e4f7-11e7-8417-7f8ec4a8e851.png)

**Comment by cmmadnat** [comment]
ปรับทั้งหมดใแห้เป็น 15px

**Comment by RDPB2-Kuer** [comment]
OK
