### ISSUE TITLE
Back : ทุก ศ. -  ขอปรับปรุงหัวข้อการบันทึกที่ตั้งศูนย์เรียนรู้

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#337]
เนื่องจากพบว่าใส่ข้อมูลสับสน จึงขอให้ปรับปรุงหัวข้อการใส่ข้อมูลดังนี้
![image](https://user-images.githubusercontent.com/30930235/34186750-38a04120-e560-11e7-8084-341785df8055.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-20 -1](https://user-images.githubusercontent.com/37333/34191694-9ecc75a2-e57b-11e7-854c-20204cb301b2.png)

**Comment by RDPB2-Kuer** [comment]
OK
