### ISSUE TITLE
Back : ศ. พอเพียง - ปรับแก้การแสดงค่าพิกัด ให้เหมือน ศ. ตามแนว

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#339]
![image](https://user-images.githubusercontent.com/30930235/34187935-683f777e-e566-11e7-9110-b4711de34b78.png)

ที่ถูกต้อง คือ รูปนี้
![image](https://user-images.githubusercontent.com/30930235/34188110-2adad2a6-e567-11e7-826c-139fb502b29b.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-20](https://user-images.githubusercontent.com/37333/34191642-31bd346a-e57b-11e7-94ec-e65fa850f46c.png)

**Comment by RDPB2-Kuer** [comment]
OK
