### ISSUE TITLE
Back : ศ.อื่นๆ - ปรับแก้การแสดงค่าพิกัดให้เหมือน ศ.ตามแนว

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#340]
![image](https://user-images.githubusercontent.com/30930235/34188235-f7d60bc2-e567-11e7-8414-b26aa7a965c9.png)

ที่ถูกต้อง คือ
![image](https://user-images.githubusercontent.com/30930235/34188272-1d981cba-e568-11e7-938e-ea321a543d23.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-20 2](https://user-images.githubusercontent.com/37333/34191627-1481fad4-e57b-11e7-8bf8-f412e67833bf.png)

**Comment by RDPB2-Kuer** [comment]
OK
