### ISSUE TITLE
Back : ทุก ศ. - ปรับ font รายละเอียดเพิ่มเติม ให้เป็น Default Font

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#341]
![image](https://user-images.githubusercontent.com/30930235/34188469-255f5818-e569-11e7-9675-d29b609d2c94.png)

**Comment by cmmadnat** [comment]
font default ได้ไหมครับ

**Comment by cmmadnat** [comment]
<img width="314" alt="screen shot 2560-12-20 at 11 14 43" src="https://user-images.githubusercontent.com/37333/34191081-00ced696-e577-11e7-8f9a-033ff19aff2b.png">

**Comment by RDPB2-Kuer** [comment]
ขอปรับปรุงให้เปลี่ยนเป็น Default font ทั้งหมด

**Comment by RDPB2-Kuer** [comment]
OK
