### ISSUE TITLE
Back : ศ.พอเพียง - ปรับขนาดของ รายละเอียดเพิ่มเติม ให้เท่ากับ ศ.อื่นๆ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#342]
ศ.พอเพียง ไม่ถูกต้อง 
![image](https://user-images.githubusercontent.com/30930235/34188779-b1fbae92-e56a-11e7-9b5b-55d00ebc87ee.png)

ขนาดที่ถูกต้อง คือ ศ.อื่นๆ
![image](https://user-images.githubusercontent.com/30930235/34188651-19ff2664-e56a-11e7-8ba3-16d30f6397f4.png)

**Comment by cmmadnat** [comment]
<img width="1280" alt="screen shot 2560-12-20 at 11 00 51" src="https://user-images.githubusercontent.com/37333/34190748-0fb29c80-e575-11e7-8197-51fd5cbe9524.png">

**Comment by RDPB2-Kuer** [comment]
OK
