### ISSUE TITLE
Back : ศ.ตามแนว - ปรับขนาดของ รายละเอียดเพิ่มเติม ให้เท่ากับ ศ.อื่นๆ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#343]
ศ. ตามแนว ที่ไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/34188861-1e6001e6-e56b-11e7-8fcd-cbced3d00e47.png)

ขนาดของศ.อื่นๆ ที่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/34188840-fcb4577c-e56a-11e7-8a86-91e8287097e2.png)

**Comment by cmmadnat** [comment]
<img width="1280" alt="screen shot 2560-12-20 at 10 59 47" src="https://user-images.githubusercontent.com/37333/34190734-f5093fec-e574-11e7-885b-43221611a0bb.png">
