### ISSUE TITLE
Front : ศ.พอเพียง - ปรับแก้การแสดงหน้าจอรายละเอียด

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#345]
![image](https://user-images.githubusercontent.com/30930235/34191266-3cc92f4c-e578-11e7-9e51-b1a0d8e0db0d.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-12-20](https://user-images.githubusercontent.com/37333/34192303-d2e91a44-e57f-11e7-80d7-327ec42e66b0.png)
ขนาดของช่องมันตรงกันไม่ได้ครับที่เขียนว่าเลื่อนกรอบให้ตรงกัน เพราะมันไปตามขนาดของหน้าจอ

**Comment by RDPB2-Kuer** [comment]
OK
