### ISSUE TITLE
Back : ศ.ตามแนว - เพิ่มการนำเข้าข้อมูล "ปีที่จัดตั้ง"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#349]
![image](https://user-images.githubusercontent.com/30930235/34318465-ee5cb7f4-e7fa-11e7-88e7-9174f1dd107d.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-02-27 at 16 20 06](https://user-images.githubusercontent.com/37333/36720264-18afd8e8-1bda-11e8-9b3b-9962014c067f.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย ขอบคุณค่ะ
