### ISSUE TITLE
Back : ศ. อื่นๆ - ปรับแก้การแสดงกรอบผู้รับผิดชอบและผู้ประสานงานให้เท่ากัน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#355]
![image](https://user-images.githubusercontent.com/30930235/34319099-96178112-e80b-11e7-9ff4-190a092f2916.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
