### ISSUE TITLE
Back : ทุก ศ. - ปรับปรุงการบันทึกข้อมูลหัวข้อ "รางวัล"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#356]
![image](https://user-images.githubusercontent.com/30930235/34319121-460c224e-e80c-11e7-8e0d-5151d0321e9e.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/34508103-c3cc90e6-f06e-11e7-95ed-44a81f749d85.png)

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
