### ISSUE TITLE
Back : ทุก ศ. - ปรับปรุงการนำเข้าหัวข้อ “รหัสไปรษณีย์” ให้เป็นการแสดงผลโดยอัตโนมัติ 

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#357]
หัวข้อ “รหัสไปรษณีย์” ปรับปรุงให้เป็นการแสดงผลโดยอัตโนมัติ ในกรณีที่มีรหัสไปรษณีย์ 2 อัน ก็แสดงให้ทั้ง 2 รหัสเพื่อให้ผู้ใช้งานเลือกอันที่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/34319178-205e4142-e80e-11e7-9996-31bfb0b02159.png)

**Comment by RDPB2-Kuer** [comment]
หญิงส่ง file ให้ทาง Mail แล้ว วันนี้

**Comment by Srikridsadaporn** [comment]
เรียบร้อย รอ Upload เข้า Production

**Comment by anucha1892** [comment]
เรียบร้อย
