### ISSUE TITLE
Back : ทุก ศ. - ขอใหัจัดเก็บข้อมูลในส่วนของ “รายละเอียด” เป็น Index เพิ่มเติม

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#358]
![image](https://user-images.githubusercontent.com/30930235/34319189-90b24e98-e80e-11e7-9fe5-0d744c2c1211.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/34508281-2abd2d6e-f070-11e7-8cac-8158d73020e9.png)

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
