### ISSUE TITLE
Front : ทุก ศ. - กรณีไม่มีรูปภาพของแผนที่ตั้งศูนย์ ขอให้แสดงเป็นสีจาง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#359]
![image](https://user-images.githubusercontent.com/30930235/34319230-3f19e888-e80f-11e7-959d-945aa787ad60.png)

**Comment by Srikridsadaporn** [comment]
ปิดนะคะ เพราะหน้าตาเปลี่ยนไป..
