### ISSUE TITLE
Back ศูนย์เรียนรู้เศรษฐกิจพอเพียง หน้าจอบันทึกข้อมูลเรียบร้อย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#36]
น้องแนต ปรับตามภาพด้วยค่ะ
เมื่อระบบแสดงผลว่าบันทึกข้อมูลเรียบร้อยแล้ว สัก 5 วินาที

![image](https://user-images.githubusercontent.com/31124544/32588456-60d0e9ea-c541-11e7-99ab-4e409291830a.png)

**Comment by Srikridsadaporn** [comment]
ยังตรวจไม่ได้ เพราะ บันทึกไม่ได้

**Comment by anucha1892** [comment]
เรียบร้อยครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
