### ISSUE TITLE
สิทธิ : รายละเอียดสิทธิการใช้งาน สำหรับ จนท. นำเข้าข้อมูล

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#364]
![image](https://user-images.githubusercontent.com/30930235/34330065-f2d996e0-e948-11e7-9831-333a51fdb68c.png)

![image](https://user-images.githubusercontent.com/30930235/34330075-06203240-e949-11e7-9d2d-18c071671489.png)

![image](https://user-images.githubusercontent.com/30930235/34330078-18183812-e949-11e7-950f-0620f6ae7a4a.png)

![image](https://user-images.githubusercontent.com/30930235/34330079-1eca7896-e949-11e7-9470-b31756564672.png)

![image](https://user-images.githubusercontent.com/30930235/34330081-384f2c6c-e949-11e7-9ee0-794fd8352414.png)

![image](https://user-images.githubusercontent.com/30930235/34330086-76c58de2-e949-11e7-9a77-18c02df91cde.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
