### ISSUE TITLE
ฺฺBack : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - ปรับแก้การบันทึกข้อมูล  "ด้าน/ ประเภท/ชนิด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#37]
น้องแนต ปรับตามภาพด้วยค่ะ

![image](https://user-images.githubusercontent.com/31124544/32590891-5cad6448-c54f-11e7-90a0-e5bd1bd37d92.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
