### ISSUE TITLE
Front : ศ. เศรษฐกิจพอเพียง - หน้าแสดงรายละเอียด ศ. ปรับภาพให้อยู่กลางกรอบ 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#371]
![image](https://user-images.githubusercontent.com/31124544/34347312-6ab3cf28-ea34-11e7-9dd0-10800b9b4a4d.png)

**Comment by RDPB2-Kuer** [comment]
OK
