### ISSUE TITLE
Front : ศ. อื่นๆ - หน้าแสดงรายละเอียด ศ. ปรับภาพให้อยู่กลางกรอบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#373]
![image](https://user-images.githubusercontent.com/31124544/34349543-332e8934-ea44-11e7-9e58-077723854b8d.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36387977-1276de9e-15cd-11e8-81fd-d426d647f7e9.png)

**Comment by RDPB2-Kuer** [comment]
OK
