### ISSUE TITLE
Back : ศ. พอเพียง - หน้าปรับปรุงข้อมูล ศ. เพิ่มคำว่า "เวลา" และปรับปรุงเวลาให้ตรงเวลาปรับปรุงจริง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#374]
![image](https://user-images.githubusercontent.com/31124544/34351136-5352be8e-ea4d-11e7-8111-dd1434493965.png)

**Comment by Srikridsadaporn** [comment]
ยังไม่เป็นปัจจุบัน  หรือยังไม่ได้ Upload ใหม่ค่ะ

**Comment by cmmadnat** [comment]
![screen shot 2561-01-09 at 13 53 55](https://user-images.githubusercontent.com/37333/34708291-8cb70c46-f544-11e7-9d3e-43b3fb2c04c3.jpg)

**Comment by anucha1892** [comment]
ทุกศูนย์ กรณีเพิ่มใหม่และปรับปรุง เวลายังไม่ถูกต้อง
เช่น บันทึกเมื่อเวลา 14:46 ระบบขึ้นเวลาในภาพ
![image](https://user-images.githubusercontent.com/33414080/34710033-515b544c-f54c-11e7-93c7-8df05468466a.png)

**Comment by anucha1892** [comment]
เรียบร้อย
