### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง -หน้าจอบันทึกข้อมูลสถานที่ตั้ง ปรับแก้การบังคับใส่ข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#38]
![image](https://user-images.githubusercontent.com/31124544/32591328-3a9d7242-c551-11e7-88ef-4704211c89d2.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
