### ISSUE TITLE
Back : ทุก ศ. - การแสดงรูปภาพศูนย์เรียนรู้ และการกำหนดภาพหลัก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#380]
มีเงื่อนไขการแสดง ดังนี้
1. รูปภาพแรกเป็นรูปหลักของศูนย์
2. รูปภาพศูนย์ฯ จะแสดงจาก "เก่า" ไป"ใหม่"
3. ในกรณีที่ต้องการเปลี่ยนรูปภาพหลักใหม่ สามารถเลือกที่หน้าจอนี้ คือ 
![image](https://user-images.githubusercontent.com/30930235/34353825-13cd4e9a-ea5d-11e7-9c0d-db6a540841d5.png)

**Comment by anucha1892** [comment]
เปลี่ยนชื่อปุ่มเป็น "ใช้เป็นรูปหลัก" และเปลี่ยนสีปุ่มเป็นสีเขียว ดังภาพ
![image](https://user-images.githubusercontent.com/33414080/34710622-b185de6c-f54e-11e7-8c97-09b1895b8853.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-01-30 at 16 22 43](https://user-images.githubusercontent.com/37333/35558144-d27ae310-05d9-11e8-92d9-166e5ec4a5a2.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย ขอบคุณค่ะ
