### ISSUE TITLE
Back : ข้อมูล ศ. อื่นๆ สำหรับนำเข้าระบบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#386]
[RDPB2-Conversion-Data-ธกส ศปร กศน-V0.2.xlsx](https://github.com/cmmadnat/rdpb2/files/1590960/RDPB2-Conversion-Data-.-V0.2.xlsx)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
