### ISSUE TITLE
Front : หน้าแรก - ปรับปรุงการแสดงรายชื่อ ศ. พอเพียง และ ศ. ตามแนว

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#388]
การแสดงข้อมูลปัจจุบัน
![image](https://user-images.githubusercontent.com/30930235/34511070-ad3901e4-f08b-11e7-8e1e-2309937e4fae.png)

ต้องการให้ปรับปรุงให้เป็นแบบนี้ คือ
<img width="1204" alt="screen shot 2560-12-26 at 15 22 38" src="https://user-images.githubusercontent.com/30930235/34511120-ff4f5d20-f08b-11e7-88c1-a955ed3eda60.png">

**Comment by cmmadnat** [comment]
<img width="1252" alt="screen shot 2561-01-08 at 16 13 55" src="https://user-images.githubusercontent.com/37333/34664539-f5cf1054-f48e-11e7-9a83-330d5236d720.png">

**Comment by cmmadnat** [comment]
แก้ไขจำนวนบรรทัดแล้วครับ 
<img width="618" alt="screen shot 2561-01-08 at 17 01 36" src="https://user-images.githubusercontent.com/37333/34666185-a66bc974-f495-11e7-8b06-6318f16b90ac.png">

**Comment by anucha1892** [comment]
เรียบร้อย
