### ISSUE TITLE
Front : หน้าแรก - ปรับปรุงการแสดงรายการ ศ. อื่นๆ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#389]
ปัจจุบันเป็นแบบนี้ ซึ่งไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/34511205-59726e14-f08c-11e7-99ed-1ca599aafc7b.png)

ต้องการปรับปรุงใหม่เป็นแบบด้านล่างนี้ โดยไม่ต้องแสดง Logo หน่วยงาน
![messageimage_1514350260029](https://user-images.githubusercontent.com/30930235/34511232-93d2cbe4-f08c-11e7-8247-cb932ead4737.jpg)

**Comment by cmmadnat** [comment]
![screenshot-2018-1-7 rdpb](https://user-images.githubusercontent.com/37333/34643141-d2cfa9c6-f351-11e7-9d54-628d2913b437.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
