### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอการบันทึกข้อมูล ปรับแก้หัวข้อรางวัล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#39]
ปรับด้วยค่ะ
![image](https://user-images.githubusercontent.com/31124544/32592065-a8214a16-c554-11e7-9e5f-42847969e760.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
