### ISSUE TITLE
Front : หน้าแสดงรายการ ศ. - ปรับปรุงให้แสดงรายการ ศ. ให้มีขนาดมาตรฐานเดียวกัน 

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#390]
ปัจจุบันเป็นแบบด้านล่างนี้ ซึ่งไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/34511296-08314b50-f08d-11e7-9b20-112324dbec81.png)

ขอให้ปรับปรุงใหม่ ให้มีรูปและข้อความเป็นมาตรฐานเดียวกัน และไม่ต้องใส่ Logo ดังนี้
![messageimage_1514350445839](https://user-images.githubusercontent.com/30930235/34511306-20cff292-f08d-11e7-9a21-12affd97f4ab.jpg)

โดยมีเงื่อนไขการแสดงข้อมูล ดังนี้
1. ศ. พอเพียง 
   -  กรณีเลือกที่หัวข้อ "ศูนย์เรียนรู้เศรษฐกิจพอเพียง" ให้แสดงหน้ารายการ ศ. โดยแสดงเฉพาะรายชื่อ ศ.พอเพียง โดยเรียงรายชื่อ ศ. ล่าสุดก่อน
   - กรณีเลือกที่ชื่อ ศ.ใด ศ. หนึ่ง ให้แสดงรายละเอียดข้อมูล ศ. นั้น 

2. ศ. ตามแนว 
   -  กรณีเลือกที่หัวข้อ "ศูนย์เรียนรู้ตามแนวพระราชดำริ" ให้แสดงหน้ารายการ ศ. โดยแสดงเฉพาะรายชื่อ ศ.ตามแนว โดยเรียงรายชื่อ ศ. ล่าสุดก่อน
   - กรณีเลือกที่ชื่อ ศ.ใด ศ. หนึ่ง ให้แสดงรายละเอียดข้อมูล ศ. นั้น 2. ศ. ตามแนว 

 2. ศ. อื่นๆ 
   -  กรณีเลือกที่หัวข้อ "ศูนย์เรียนรู้อื่นๆ" ให้แสดงหน้ารายการ ศ. โดยแสดงเฉพาะรายชื่อ ศ.อื่นๆ ของทุกหน่วยงาน โดยเรียงรายชื่อ ศ. ล่าสุดก่อน
   - กรณีเลือกที่ชื่อ ศ. ของหน่วยงานใดหน่วยงานหนึ่ง ให้แสดงหน้ารายการ ศ. โดยแสดงเฉพาะรายชื่อ ศ.อื่นๆ ของหน่วยงานที่เลือก โดยเรียงรายชื่อ ศ. ล่าสุดก่อน

**Comment by cmmadnat** [comment]
แก้ไขเฉพาะส่วนของ layout อย่าเพิ่งปิดครับ

**Comment by Srikridsadaporn** [comment]
Closed ไปก่อน
