### ISSUE TITLE
Front : หน้าแสดงรายการ ศ. - ขอให้เพิ่มการแสดงจำนวนศ. ด้วย

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#391]
ขอให้แสดงจำนวน ศ. เรียนรู้แต่ละประเภท หรือ ศ.อื่นๆ แต่ละหน่วยงาน เหมือน จำนวนโครงการฯ ดังนี้
![image](https://user-images.githubusercontent.com/30930235/34513347-6f8b2c8c-f09a-11e7-8af9-8c0dec7bd719.png)

**Comment by cmmadnat** [comment]
![screenshot-2018-1-7 rdbp](https://user-images.githubusercontent.com/37333/34642800-14bc4156-f34c-11e7-8e78-b713ffaab2a4.png)

**Comment by Srikridsadaporn** [comment]
ไม่น่าจะใช่นะคะ ต้องเป็นจำนวนรวมของแต่ละหน่วยงานเมื่อเลือกหน่่วยงานนั้นๆ

**Comment by anucha1892** [comment]
เรียบร้อย
