### ISSUE TITLE
Back : จัดการผู้ใช้งานระบบ - ปรับปรุงขอบเขตผู้รับผิดชอบ

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#393]
ขอให้จัดเรียงภาคและจังหวัดตามตัวอย่างด้านล่าง
![image](https://user-images.githubusercontent.com/33414080/34662506-c6a839d2-f483-11e7-9658-7353d647aabc.png)

**Comment by Srikridsadaporn** [comment]
OK เรียบร้อย
