### ISSUE TITLE
Front : ศ.อื่นๆ - ปรับแก้การแสดงชื่อหน่วยงาน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#394]
ให้เพิ่มข้อความ "สังกัด : " ก่อนชื่อหน่วยงาน และเปลี่ยน font และขนาดของข้อความให้เป็นขนาดเดียวกับรายละเอียด แต่เพิ่ม Bold
![image](https://user-images.githubusercontent.com/30930235/34662936-91b3d0f8-f486-11e7-9e37-fd56dde39584.png)

**Comment by cmmadnat** [comment]
<img width="1256" alt="screen shot 2561-01-08 at 16 11 08" src="https://user-images.githubusercontent.com/37333/34664456-919f3de8-f48e-11e7-8e65-6306e5a4b42e.png">

**Comment by anucha1892** [comment]
เรียบร้อย

**Comment by anucha1892** [comment]
ส่วนรายละเอียดให้แสดงแค่ 3 บรรทัด เหมือนกับ ศ.พอเพียง และ ศ.ตามแนวฯ

**Comment by anucha1892** [comment]
เรียบร้อย
