### ISSUE TITLE
Back : จัดการผู้ใช้งานระบบ - แก้ไขชื่อในส่วนผู้ใช้งาน

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#398]
แก้ไขชื่อผู้ใช้งาน ดังภาพ
![image](https://user-images.githubusercontent.com/33414080/34926259-ae3d07e4-f9e0-11e7-9ec9-14e6d122aecf.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
