### ISSUE TITLE
 Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอบันทึก ข้อมูลทั่วไป

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#4]
@cmmadnat น้องแนตคะ รบกวนปรับรายละอียดตามภาพ
![image](https://user-images.githubusercontent.com/31124544/32319889-983d46ec-bfee-11e7-90a0-cb02f37d06fe.png)

**Comment by RDPB2-Kuer** [comment]
พี่ขอปรับปรุง Design ใหม่ ดังนี้
![screen shot 2560-11-03 at 13 37 58](https://user-images.githubusercontent.com/30930235/32362479-5693057a-c09c-11e7-939f-77191a75606e.png)

**Comment by RDPB2-Kuer** [comment]
ข้อ 4.3 ขอปรับปรุง ดังนี้
1. ปรับปรุง Drop Down List ที่ให้เลือก ขอเพิ่มตัวแรก เป็น " = เลือก ="
2. สถานะศูนย์เรียนรู้ ค่า Default คือ "ศูนย์เรียนรู้"
3. หัวข้อ "รางวัล" ไม่บังคับให้ใส่ข้อมูล
4. หัวข้อ "..../รายละเอียด" ขอให้ขยายช่องใส่ข้อมูลให้ยาวขึ้น

**Comment by RDPB2-Kuer** [comment]
ข้อ 4.4 ขอปรับแก้ ดังนี้
![image](https://user-images.githubusercontent.com/30930235/32362890-0f54ce84-c09f-11e7-96bf-3ad0e6f2a2d8.png)

**Comment by cmmadnat** [comment]
<img width="1280" alt="screen shot 2560-11-03 at 16 56 20" src="https://user-images.githubusercontent.com/37333/32368311-f2708c5e-c0b7-11e7-85e2-b20eff217b53.png">
<img width="1280" alt="screen shot 2560-11-03 at 16 56 25" src="https://user-images.githubusercontent.com/37333/32368312-f2c1c89e-c0b7-11e7-8d3f-badc09ea3791.png">

**Comment by cmmadnat** [comment]
ขาดเรื่องหัวข้อหดนะครับ

**Comment by RDPB2-Kuer** [comment]
ยังมีอีกนะ Font ข้อมูลบันทึก ขอให้เปลี่ยนเป็น Default Font ทุกอันด้วยคะ
![image](https://user-images.githubusercontent.com/30930235/32373572-77f344e8-c0cc-11e7-8921-d41b3efb9be2.png)

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/32373669-f27a06fc-c0cc-11e7-8008-19f200132118.png)

**Comment by cmmadnat** [comment]
font พอไม่เท่านี้แล้วช่องมันน่าเกลียดอะครับ อาจะต้องรอปรับซักหน่อย
เดี๋ยวขอปรับส่วนของ ประเภทก่อนนะครับ

**Comment by Srikridsadaporn** [comment]
ปรับแยกแล้ว...Closed ไปใช้ #28-30
