### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอบันทึกข้อมูล ปรับแก้ค่า Default ด้าน/ประเภท/ชนิด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#40]
![image](https://user-images.githubusercontent.com/31124544/32592254-7d8edf1a-c555-11e7-8a61-e3cf1cd08b44.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
