### ISSUE TITLE
Back : หน้าการตั้งค่า สิทธิ์ผู้ใช้งาน - ปรับ Font ของรายการข้อมูลเป็น Default Font

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#402]
![image](https://user-images.githubusercontent.com/31124544/34971974-fc4b945c-fab0-11e7-8758-59e3866b38a0.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-01-30 at 16 18 35](https://user-images.githubusercontent.com/37333/35557945-3e23d366-05d9-11e8-854d-585703a31551.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย..ขอบคุณค่ะ
