### ISSUE TITLE
Back : จัดการผู้ใช้งานระบบ  ปรับแก้ชื่อกลุ่มระบบงาน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#405]
![image](https://user-images.githubusercontent.com/31124544/35138436-225f51fc-fd21-11e7-981a-0d4d6bc7ecf5.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-01-30 at 16 16 50](https://user-images.githubusercontent.com/37333/35557856-ffa363c2-05d8-11e8-8622-57c556811b52.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
