### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอบันทึกข้อมูล  ปรับขนาด Font ข้อมูลทั่วไป

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#41]
![image](https://user-images.githubusercontent.com/31124544/32592464-6c30d6dc-c556-11e7-9a87-5264b992d89e.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
