### ISSUE TITLE
Back : จัดการผู้ใช้งานระบบ -ตั้งค่าผู้ใช้งานเปลี่ยนปุ่มแจ้งผลการบันทึกข้อมูลให้เป็นแบบเดียวกัน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#410]
![image](https://user-images.githubusercontent.com/31124544/35141257-033e361a-fd2d-11e7-838a-3f211d167ffa.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-01-30 at 16 12 43](https://user-images.githubusercontent.com/37333/35557694-6bfa77a0-05d8-11e8-8ac1-c984157bff51.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
