### ISSUE TITLE
Back : หน้าจัดการสิทธิ์ - กลุ่มผู้ใช้งาน ปรับกลุ่มข้อมูลศูนย์เรียนรู้อื่นๆ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#411]
![image](https://user-images.githubusercontent.com/31124544/35145287-da889e60-fd39-11e7-9f65-275211ae5210.png)

**Comment by cmmadnat** [comment]
แยกได้แค่นี้อะครับ
![screen shot 2561-01-30 at 16 03 21](https://user-images.githubusercontent.com/37333/35557259-2c60960c-05d7-11e8-9218-6712aa48b8b7.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
