### ISSUE TITLE
Back : ศ.อื่นๆ (กอ.รมน.- กศน.) ข้อมูลที่จะ Upload เข้าสู่ระบบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#414]
[RDPB2-Conversion-Data-กอรมน-V3.3Resubmit.xlsx](https://github.com/cmmadnat/rdpb2/files/1654280/RDPB2-Conversion-Data-.-V3.3Resubmit.xlsx)

**Comment by cmmadnat** [comment]
[Data conversion.zip](https://github.com/cmmadnat/rdpb2/files/1671316/Data.conversion.zip)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย ขอบคุณค่ะ
