### ISSUE TITLE
Back : จัดการผู้ใช้งาน - ปรับขยายขนาดช่อง "ชื่อกลุ่ม" และเพิ่มช่องว่างระหว่างข้อมูลตามภาพด้านใน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#418]
![image](https://user-images.githubusercontent.com/31124544/35546353-8b9ddf16-05a6-11e8-8193-dc64fe790163.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-01-30 at 15 59 38](https://user-images.githubusercontent.com/37333/35557072-9d170fc6-05d6-11e8-8601-e1e623084fb5.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
