### ISSUE TITLE
Back : การตั้งค่า  หน่วยงาน  ปรับแก้การยืนยันการลบข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#419]
![image](https://user-images.githubusercontent.com/31124544/35322112-a6d4ca54-011b-11e8-9129-1fdc63ed218b.png)

**Comment by cmmadnat** [comment]
ผมแก้สีไม่ได้ครับ
![screen shot 2561-01-30 at 15 55 47](https://user-images.githubusercontent.com/37333/35556871-10c57954-05d6-11e8-8d3f-445d55a7bd39.jpg)

**Comment by Srikridsadaporn** [comment]
ค่ะ
