### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอบันทึกข้อมูล ปรับขนาด Font ข้อมูลที่บันทึก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#42]
![image](https://user-images.githubusercontent.com/31124544/32592672-67584e8c-c557-11e7-86db-c51a9e190187.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
