### ISSUE TITLE
Back : หน้าจัดการผู้ใช้งานระบบ จัดเรียงกลุ่มที่จัดการได้ให้เป็นแบบเดียวกับกลุ่มผู้ใช้งาน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#421]
![image](https://user-images.githubusercontent.com/31124544/35324395-309d72e8-0123-11e8-8841-aed47c465ca1.png)

**Comment by cmmadnat** [comment]
จะทำได้ยังไงครับ อันนี้ไม่เข้าใจเลยครับว่าให้เป็นแบบเดียวกันหมายความว่ายังไง

คือหมายถึงว่าจะต้องมี อีกอย่างเหรอว่ากลุ่มนั้นคือประเภทไหน?

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
