### ISSUE TITLE
Front : หน้าแรก เรียงลำดับรายการ ศ.พอเพียง และตามแนวใหม่ตามภาพ 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#423]
![image](https://user-images.githubusercontent.com/31124544/35333220-80f50176-0140-11e8-909b-c4021c1cabdc.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36387831-9aac038a-15cc-11e8-8d53-00e689d44a86.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่่ะ
