### ISSUE TITLE
Front  : หน้าแรก  รายการศูนย์เรียนรู้หน่วยงาน  เปลียนจากชื่อสังกัดเป็น "ชื่อจังหวัด"

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#424]
![image](https://user-images.githubusercontent.com/31124544/35333516-992c6bfc-0141-11e8-8c57-c71d149dfeb8.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36387570-e6e52a3e-15cb-11e8-8612-73c9a2a63dab.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย ขอบคุณค่ะ
