### ISSUE TITLE
ฺBack : ตั้งค่ากลุ่มผู้ใช้งาน จัดเรียงให้เป็นหมวดหมู่

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#426]
![image](https://user-images.githubusercontent.com/31124544/35334328-91c2f9d2-0144-11e8-93f4-a74987b14086.png)

**Comment by cmmadnat** [comment]
จะจัดยังไงอะครับพี่ เอาจริงๆ ก็จัดไม่ได้นะครับ เพราะว่าไม่งั้นก็ต้องให้เลือกอีกว่าเป็นประเภทไหน

**Comment by Srikridsadaporn** [comment]
เรียงลำดับตามตัวอักษรได้ไหมค่ะ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
