### ISSUE TITLE
Front :  หน้าแรก  ปรับแก้เมนูหลัก ตามภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#429]
![image](https://user-images.githubusercontent.com/31124544/35496801-2092fac8-04fa-11e8-8b01-f148b862c23b.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/35548661-9e916c34-05b3-11e8-9a79-4837002f1ffc.png)

**Comment by Srikridsadaporn** [comment]
น้องแนตน่าจะเข้าใจผิดล่ะคะ หน้า "หน่วยงานร่วม" **_จะแสดงรายละเอียดตาม  IR Front : เพิ่มหน้า "หน่วยงานร่วม" โดยมีการแสดงข้อมูลดังภาพตัวอย่าง #431_**

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
