### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอบันทึกข้อมูล การตรวจสอบข้อมูลบังคับ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#43]
กรณีที่ผู้ใช้กดปุ่มบันทึกข้อมูล  ระบบต้องตรวจสอบว่ามีการใส่ข้อมูลบังคับถ้วนหรือยัง  ถ้ายังไม่ครบถ้วนให้แสดง ข้อความเตือน เหมือนในระบบระยะที่ 1 (โครงการ)และเมื่อกดปุ่ม OK ให้ระบบไฮไลท์ ฟิลด์บังคับที่ยังไม่ได้บันทึก

![image](https://user-images.githubusercontent.com/31124544/32592951-801083b2-c558-11e7-8431-3e4936345857.png)

**Comment by cmmadnat** [comment]
แก้ไขแล้วครับ

**Comment by Srikridsadaporn** [comment]
@cmmadnat  ยังไม่เช็ค ด้าน/ประเภท/ชนิด  และ จังหวัด ทีเป็นฟิลด์บังคับ

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
