### ISSUE TITLE
Front : ปรับแก้หน้าแรกรายการส่วนล่าง 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#430]
![image](https://user-images.githubusercontent.com/31124544/35393577-ef30ef60-0217-11e8-85c0-9007ff5f300c.png)

**Comment by cmmadnat** [comment]
ขอทราบเพิ่มเติมครับว่าเรียงตามอะไรครับ

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/35548672-b50b9d90-05b3-11e8-88dc-2e3ae1382556.png)

**Comment by Srikridsadaporn** [comment]
น้องแนตน่าจะเข้าใจผิดละ รบกวนปรับใหม่ตามรายละเอียดในภาพนะคะ
![image](https://user-images.githubusercontent.com/31124544/35553843-14efff0e-05cc-11e8-8d56-e16106b045b6.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
