### ISSUE TITLE
Front : หน้ารายการศูนย์เรียนรู้ของแต่ละหน่วยงาน - ปรับแก้สีให้ตรงกับสีที่หน่วยงานเลือกไว้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#432]
![image](https://user-images.githubusercontent.com/31124544/35424222-c08352da-0284-11e8-9ae9-165710ee82b6.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-02-01 at 08 55 59](https://user-images.githubusercontent.com/37333/35657180-c81f1170-072d-11e8-8262-dc229921a43a.jpg)

**Comment by Srikridsadaporn** [comment]
หมายถึงหน้ารายการของศูนย์เรียนรู้ของแต่ละหน่วยงาน ดูตามภาพแรก
