### ISSUE TITLE
Front : หน้ารายการศูนย์เรียนรู้ของแต่ละหน่วยงาน - ปรับจำนวนศูนย์เรียนรู้ให้ถูกต้อง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#433]
![image](https://user-images.githubusercontent.com/31124544/35494073-8353f654-04ea-11e8-81e5-00795f59deb0.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-02-01 at 08 55 59](https://user-images.githubusercontent.com/37333/35657174-be4c7c96-072d-11e8-9c2c-2565a677a773.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่่ะ
