### ISSUE TITLE
Back : ศ.อื่นๆ (ทุกหน่วยงาน) - เลือกค้นหาจากชื่อจังหวัด ระบบแสดงรายการที่ค้นหาไม่ถูกต้อง

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#434]
จากภาพ เลือกหน่วยงาน "กอ.รมน.-กศน." แล้วเลือกค้นหา จังหวัด "ชุมพร" ระบบแสดงจังหวัด "กรุงเทพมหานคร" ซึ่งไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/33414080/35496231-de47e194-04f7-11e8-8c92-c9c08e3a79bc.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/35548972-86556e52-05b5-11e8-91cb-85742b1acaf9.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
