### ISSUE TITLE
Back : ศ.อื่นๆ (กอ.รมน.-กศน. ,ส.ป.ก.) - เลือกค้นหา "ผู้รับผิดชอบศูนย์" ระบบไม่แสดงรายการที่ค้นพบ

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#435]
จากภาพ เลือกหน่วยงาน "กอ.รมน.-กศน." แล้วเลือกค้นหาผู้รับผิดชอบศูนย์ "น.ส.อุไรวรรณ อุดมฉวี" ระบบไม่แสดงรายการที่ค้นพบ
![image](https://user-images.githubusercontent.com/33414080/35496569-0698791e-04f9-11e8-817d-9e9760dc8708.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-01-29 at 17 05 21](https://user-images.githubusercontent.com/37333/35504795-9df58e74-0516-11e8-85a4-3a97c47946ee.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
