### ISSUE TITLE
Back : ศ.ตามแนว เพิ่มตัวเลือก "ประเภท"

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#436]
ศ.ตามแนว เพิ่มตัวเลือก "ประเภท" ดังนี้
1. กลุ่มการเลี้ยงชันโรง
2. กลุ่มแม่บ้านเกษตรกร
3. กลุ่มวิสาหกิจชุมชนแปรรูปผลิตภัณฑ์ประมง 
4. หญ้าแฝก

**Comment by cmmadnat** [comment]
<img width="295" alt="screen shot 2561-01-29 at 16 41 24" src="https://user-images.githubusercontent.com/37333/35503653-56179d70-0513-11e8-86b4-e35f81d6e155.png">

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
