### ISSUE TITLE
Back : ศ.อื่นๆ หน้ารายการศูนย์เรียนรู้  การค้นหาด้วยเงื่อนไข"จังหวัด" ผลที่ได้ไม่ตรงเงื่อนไข

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#437]
![image](https://user-images.githubusercontent.com/31124544/35545152-4052ee3a-05a0-11e8-8a77-d9a7e7a8babd.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/35548985-96074c4e-05b5-11e8-8ae3-fc767afce7b8.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
