### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอบันทึกข้อมูล เลือกภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#44]
![image](https://user-images.githubusercontent.com/31124544/32593315-06bbfa80-c55a-11e7-836c-945c61adca8e.png)

**Comment by cmmadnat** [comment]
<img width="1036" alt="screen shot 2560-11-12 at 16 25 41" src="https://user-images.githubusercontent.com/37333/32697580-29437bbe-c7c6-11e7-8141-99ff4662517c.png">

**Comment by Srikridsadaporn** [comment]
ยังใช้ไม่ได้ค่ะ เมื่อเลือกรูปและSave แล้ว ยังไม่ขึ้นเป็นภาพที่เลือก
![image](https://user-images.githubusercontent.com/31124544/32709763-8e78992a-c865-11e7-820f-a7ba5184faac.png)

**Comment by Srikridsadaporn** [comment]
ปรับแก้แล้ว
