### ISSUE TITLE
Front : หน้ารายละเอียดศูนย์เรียนรู้ ศ.อื่นๆ เปลี่ยนชื่อแผนที่ตั้ง เป็น "แผนผังที่ตั้ง" และสลับตำแหน่งกับ "นำทางบนแผนที่"

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#442]
![image](https://user-images.githubusercontent.com/31124544/35850746-6bc4a604-0b58-11e8-8aea-c250e920face.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36387473-9f71f286-15cb-11e8-85f6-32929ca61bd8.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่่ะ
