### ISSUE TITLE
Front : หน้าผลการค้นหาศ. เอา เมนูบาร์ "พระราชดำริ" และ "แนวคิดทฤษฎีฯ " ออก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#445]
![image](https://user-images.githubusercontent.com/31124544/35954238-254b8990-0cbb-11e8-9820-ad2fbcf8a09a.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36387236-efc3a000-15ca-11e8-9aa2-9443e5faccc7.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
