### ISSUE TITLE
Front : ปรับแก้รายการจาก "ศูนย์การเรียนรู้อื่นๆ " เป็น  "ศูนย์เรียนรู้อื่นๆ " ในรายการส่วนล่าง และเอา "ศูนย์เรียนรู้ สำนักงาน กปร." ออก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#446]
![image](https://user-images.githubusercontent.com/31124544/36009214-cbf07c3e-0d7d-11e8-8177-e07e9ac4cf7d.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36387047-6817dbbc-15ca-11e8-9e41-98a6091ecbee.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36387206-dcb8db06-15ca-11e8-8b64-d2efb3f70461.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่่ะ
