### ISSUE TITLE
Front :  หน้าหน่วยงานร่วม ไม่ต้องแสดงข้อมูล "สำนักงาน กปร."

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#447]
![image](https://user-images.githubusercontent.com/31124544/35954478-6b803dc4-0cbc-11e8-8399-425b57e554d7.png)

**Comment by Srikridsadaporn** [comment]
ยังไม่แก้หรือไม่ Upload ไม่แน่ใจค่ะ รบกวนเช็คใหม่
![image](https://user-images.githubusercontent.com/31124544/36405300-8e142c82-1622-11e8-8d64-7c863ab9b68a.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-02-27 at 16 10 36](https://user-images.githubusercontent.com/37333/36719825-c5f4c150-1bd8-11e8-9138-77c5f5a5b78e.jpg)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
