### ISSUE TITLE
Front : หน้าแรก ปรับแก้เมนูบาร์ ส่วน List ศูนย์เรียนรู้ ไม่ต้องแสดง  "ศูนย์เรียนรู้สำนักงาน กปร."ตามภาพด้านใน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#448]
![image](https://user-images.githubusercontent.com/31124544/35954642-65f5d5ca-0cbd-11e8-896c-1d20590e2e95.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36386995-36bb795c-15ca-11e8-8d2f-5bb35696dd1a.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่่ะ
