### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอแสดงรายการข้อมูล การกำหนดเงื่อนไขการค้นหา

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#45]
![image](https://user-images.githubusercontent.com/31124544/32594808-fd6cf30c-c55f-11e7-84be-5ddeb3613048.png)

**Comment by cmmadnat** [comment]
แก้ไขแล้วครับ

**Comment by Srikridsadaporn** [comment]
ยังไม่สามารถใช้งานได้

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
