### ISSUE TITLE
หน่วยงานร่วม : ให้แสดงผลแบบ Auto ในหน้า Front ทั้งส่วนข้อความและ Logo

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#454]
รบกวนตรวจสอบการแสดงผลของ Logo ด้วย

![image](https://user-images.githubusercontent.com/31124544/36406690-2e5ffdbc-162b-11e8-8387-6a49c16b9f12.png)

**Comment by cmmadnat** [comment]
มันจะอัพเดทหลังจากหน้าแรกเปิดประมาณ 15 ครั้งไม่ก็ server ปิดครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
