### ISSUE TITLE
Front : ทุก ศ. - กรณีไม่มีรูปภาพของแผนผังที่ตั้ง ขอให้แสดงเป็นสีจาง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#455]
![image](https://user-images.githubusercontent.com/31124544/36411503-9886567e-1648-11e8-8952-32393f55df70.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-02-27 at 16 09 24](https://user-images.githubusercontent.com/37333/36719765-9dcc76c8-1bd8-11e8-92ab-c9fe7c7a567c.jpg)

**Comment by Srikridsadaporn** [comment]
OK ขอบคุณค่ะ
