### ISSUE TITLE
Service สำหรับ Mobile -ปรับลำดับการเรียงหน่วยงานในการค้นหาขั้นสูง ด้วยการเรียงลำดับการเลือกหน่วยงาน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#457]
รบกวนปรับลำดับการเรียงหน่วยงานในการค้นหาขั้นสูง ด้วยการเลือกหน่วยงานดังนี้
ศูนย์เรียนรู้เศรษฐกิจพอเพียง
ศูนย์เรียนรู้ตามแนวพระราชดำริฯ
ศูนย์เรียนรู้ กอ.รมน.-กศน.
ศูนย์เรียนรู้ ธ.ก.ส.
ศูนย์เรียนรู้ ศปร.
ศูนย์เรียนรู้ ทบ.
ศูนย์เรียนรู้ ทร.
ศูนย์เรียนรู้ ทอ.
ศูนย์เรียนรู้ นทพ.
ศูนย์เรียนรู้ บช. ตชด.
ศูนย์เรียนรู้ ส.ป.ก.

**** พี่แนตคะรบกวนเรียงลำดับตามด้านบนด้วยนะคะ ****

![image](https://user-images.githubusercontent.com/31124544/36413994-2d4be95e-1653-11e8-809a-c98baaffc957.png)

**Comment by cmmadnat** [comment]
ส่วนของ พอเพียงกับตามแนวพระราชดำริ อาจจะเหมือนเดิม ถ้าคุยกับ mobile นะครับ
แต่ส่วนของผลการค้นหาของหน่วยงานต่างๆ ผมจะจัดให้ตามที่ขอนะครับ (ไม่แน่ใจจะตรงกันรึเปล่า)

**Comment by cmmadnat** [comment]
ขอลองคุยกับ mobile ก่อนนะครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
