### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - หน้าจอรูปภาพ 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#46]
![image](https://user-images.githubusercontent.com/31124544/32595199-86fab180-c561-11e7-9681-f5ed5d968717.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32644856-cd9de12e-c616-11e7-880e-7992d1ef458b.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
