### ISSUE TITLE
PHASE 1 : ปรับปรุงชื่อ ในพระองค์

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#461]
น้องแนตคะ รบกวนดำเนินการดังนี้ค่ะ

1. เพิ่มพระนาม ร.10 เป็น "สมเด็จพระเจ้าอยู่หัวมหาวชิราลงกรณ บดินทรเทพยวรางกูร"  

2. เปลี่ยนจาก "พระบาทสมเด็จพระเจ้าอยู่หัว" เป็น "พระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช"    
  
3.  ส่วน "สมเด็จพระบรมโอรสาธิราช ฯ สยามมกุฎราชกุมาร" ที่เคยใช้ในชื่อโครงการควรคงเดิมเพื่อให้ทราบว่าโครงการจัดตั้งในสมัยที่ดำรงพระยศนี้

**Comment by anucha1892** [comment]
เรียบร้อย
