### ISSUE TITLE
Back : ศูนย์เรียนรู้ตามแนวพระราชดำริฯ - ปรับแก้ Icon

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#47]
![image](https://user-images.githubusercontent.com/31124544/32598501-897fce80-c56c-11e7-9d92-da87b2442104.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32644192-aaa37dcc-c612-11e7-8b35-61d1fd9a7236.png)
แก้อยู่แล้ว

**Comment by Srikridsadaporn** [comment]
รบกวนปรับ

![image](https://user-images.githubusercontent.com/31124544/32645229-d3c4c52a-c618-11e7-8d1c-333781abee48.png)

**Comment by cmmadnat** [comment]
ทำไมมันดูบี้ๆ ลงหละครับ

**Comment by Srikridsadaporn** [comment]
ปรับให้ขนาดและรูปแบบเหมือนกับ ศูนย์เรียนรู้เศรษฐกิจ ศูนย์เรียนรู้อื่นๆ และศูนย์ศึกษาการพัฒนา 
![image](https://user-images.githubusercontent.com/31124544/32706183-dd066b5c-c84d-11e7-8c84-17c4926805c5.png)

**Comment by cmmadnat** [comment]
อาจจะต้องขอไฟล์ต้นฉบับที่ไม่มีกรอบแดงอีกรอบครับ

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
