### ISSUE TITLE
Back : ศูนย์เรียนรู้ตามแนวพระราชดำริ หน้าจอรายการข้อมูล ปรับขนาด Header

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#48]
![image](https://user-images.githubusercontent.com/31124544/32599449-2c2f92f8-c56f-11e7-95ed-d5d1ac2de524.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32644178-95d4dd3c-c612-11e7-8c83-f59d1f42b556.png)

**Comment by Srikridsadaporn** [comment]
น้องแนตคะ  จากที่มีการคุยล่าสุด  เราจะใช้สถานะศูนย์เรียนรู้ โดยเป็น "ศูนย์เรียนรู้" กับ "พื้นที่เป้าหมาย" ดังนั้น  รบกวนปรับ 
![image](https://user-images.githubusercontent.com/31124544/32705871-39da6ba6-c84b-11e7-8141-bc3c3352e0be.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
