### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง หน้าจอแสดงรายการ ปรับขนาด Font การค้นหา

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#49]
![image](https://user-images.githubusercontent.com/31124544/32599668-c419d8f8-c56f-11e7-8788-f5080957aefc.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
