### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง-หน้าจอบันทึกข้อมูลสถานที่ตั้ง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#5]
รบกวนปรับด้วยนะคะน้องแนต @cmmadnat 
![image](https://user-images.githubusercontent.com/31124544/32318512-18f0bd8c-bfea-11e7-81ce-456fdfc03f4d.png)

**Comment by RDPB2-Kuer** [comment]
ข้อ 5.2 ขอปรับแก้ ดังนี้
![image](https://user-images.githubusercontent.com/30930235/32363726-3f6059c8-c0a3-11e7-89ad-874ba00a91a2.png)

**Comment by RDPB2-Kuer** [comment]
ข้อ 5.3 เปลี่ยนสีปุ่ม ยกเลิก ให้เป็น สีแดง

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32425353-123d3cd8-c2e5-11e7-95fa-cfcc4bd637da.png)

**Comment by cmmadnat** [comment]
เพิ่งเห็นคอมเม้นต์ถัดมา กำลังแก้ครับ

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32425946-764ddd28-c2e9-11e7-81e7-9710d539aa49.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32429470-624ff338-c2fd-11e7-93cc-0ced252033b8.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32429521-8b77e2ac-c2fd-11e7-9efc-d32d4a5fa2d5.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32430646-c163cdc2-c302-11e7-99df-69b4b89e2f9a.png)

**Comment by Srikridsadaporn** [comment]
ปิดนะคะ ...น้องแนตแก้ครบแล้ว (รอเช็คหลังการ Update อีกครั้ง
