### ISSUE TITLE
ฺBack : ศูนย์เรียนรู้ตามแนวพระราชดำริ หน้าจอแสดงรายการ ปรับขนาด Font การค้นหา

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#50]
![image](https://user-images.githubusercontent.com/31124544/32642851-a7032a54-c609-11e7-8252-d02514324a2b.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32644136-5214c3fa-c612-11e7-830f-21614728bbaa.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
