### ISSUE TITLE
Back : ศูนย์เรียนรู้ตามแนวพระราชดำริ หน้าจอบันทึกข้อมูลทั่วไป  ปรับ Font 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#51]
![image](https://user-images.githubusercontent.com/31124544/32643366-8db2a7ec-c60d-11e7-91d7-d60dacac8901.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32644114-214c5684-c612-11e7-923f-8dca610ccfdf.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
