### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง - ทดสอบ Icon ใหม่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#52]
![image](https://user-images.githubusercontent.com/30930235/32709411-c7613dd0-c862-11e7-9f24-a4deac38e177.png)

![image](https://user-images.githubusercontent.com/30930235/32709451-07219df2-c863-11e7-9994-e55a4fbbb476.png)

**Comment by Srikridsadaporn** [comment]
ออกแบบปุ่มเรียบร้อยแล้ว  รอทดสอบการใช้งานปุ่ม

**Comment by RDPB2-Kuer** [comment]
ออกแบบปุ่มเรียบร้อย
