### ISSUE TITLE
ฺBack : ศูนย์เรียนรู้เศรษฐกิจพอเพียง หน้าจอบันทึกข้อมูลทั่วไป  ฟิลด์บังคับใส่ข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#53]
![image](https://user-images.githubusercontent.com/31124544/32712407-fb017f38-c876-11e7-86a5-35caee0a753b.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
