### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง บันทึกข้อมูลสถานที่ตั้ง- ฟิลด์บังคับใส่ข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#54]
![image](https://user-images.githubusercontent.com/31124544/32712488-7d5e8e94-c877-11e7-9525-0424037118fe.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
