### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - หน้าบันทึกข้อมูล การทำงานของปุ่มยังไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#55]
![image](https://user-images.githubusercontent.com/30930235/32766291-e215534e-c940-11e7-839f-7ebdaeefb078.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15 -8](https://user-images.githubusercontent.com/37333/32825244-db6bd0b4-ca16-11e7-910f-9bb707b33c96.png)
ใช้ได้แล้วครับ เพิ่ม confirm ก่อนลบแล้ว

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
