### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - หน้าบันทึกรูปภาพ & เอกสาร เปลี่ยนสีปุ่มยกเลิก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#56]
![image](https://user-images.githubusercontent.com/30930235/32766385-55ba914c-c941-11e7-8a4c-6326323608b3.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15 -7](https://user-images.githubusercontent.com/37333/32825088-2b14b50a-ca16-11e7-8b66-b1ff60ba3168.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย  ขอบคุณคะ
