### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - หน้าบันทึกรูปภาพ & เอกสาร ให้ลบปุ่มด้านบนออก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#57]
![image](https://user-images.githubusercontent.com/30930235/32766506-dd3f1d5e-c941-11e7-85a0-7293b57e8bca.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15 -6](https://user-images.githubusercontent.com/37333/32825047-fcae2836-ca15-11e7-9200-cf04f3eb5f74.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อยแล้ว...ขอบคุณค่ะ
