### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - หน้าบันทึกรูปภาพ & เอกสาร ให้ลบกรอบออก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#58]
![image](https://user-images.githubusercontent.com/30930235/32766558-266366ac-c942-11e7-8ab2-1c18bfc4bded.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15 -5](https://user-images.githubusercontent.com/37333/32825020-df8ec800-ca15-11e7-993d-74d0ca636adc.png)

**Comment by RDPB2-Kuer** [comment]
ขอโทษด้วย ขอให้ปรับแก้เป็นแบบเดิม เนื่องจากหน้าอื่นๆ เป็นแบบนี้ หากปรับแก้ต้องทำทั้งหมด

**Comment by anucha1892** [comment]
ขอให้ปรับรูปแบบให้เหมือนกันทุกศูนย์เรียนรู้ ซึ่งตอนนี้แนตปรับเฉพาะ ศ.เศรษฐกิจพอเพียง แต่ศูนย์ฯที่เหลือแนตไม่ได้ปรับครับ

**Comment by Srikridsadaporn** [comment]
ปรับเรียบร้อยแล้ว ปิด
