### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - หน้าแสดงรายการข้อมูล ปรับสีพื้น Highlight icon ให้จางลง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#59]
![image](https://user-images.githubusercontent.com/30930235/32766709-b69d7bb8-c942-11e7-9657-86070ab5017c.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15 -4](https://user-images.githubusercontent.com/37333/32824855-349afff4-ca15-11e7-9173-bb8edd680f87.png)
ดูแต่สีนะครับ อ่อนพอไหมครับ

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
