### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอบันทึกข้อมูลรูปภาพ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#6]
น้องแนตคะ   @cmmadnat รบกวนปรับตามภาพ

![image](https://user-images.githubusercontent.com/31124544/32319548-8a1a47c8-bfed-11e7-8584-f442e844adae.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32477630-49458ef6-c3b2-11e7-96e4-22f1f6130d0c.png)
