### ISSUE TITLE
Back : ปรับแก้หน้าจอ main memu - ชื่อศ.

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#60]
![image](https://user-images.githubusercontent.com/30930235/32767026-3528bd5c-c944-11e7-9156-b3c452fc407b.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15 -2](https://user-images.githubusercontent.com/37333/32824757-c9ab683c-ca14-11e7-88eb-2c324182206a.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15 -3](https://user-images.githubusercontent.com/37333/32824783-e6e895fa-ca14-11e7-8b5c-74cb0daafe37.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย  ขอบคุณค่ะ
