### ISSUE TITLE
Back : ปรับแก้หน้าจอ main menu การจัดกลุ่ม function

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#61]
![image](https://user-images.githubusercontent.com/30930235/32767144-aa6df2d0-c944-11e7-88b6-91731af44031.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15 -1](https://user-images.githubusercontent.com/37333/32824617-35622c42-ca14-11e7-948b-77b5dc054e73.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย   ขอบคุณคะ
