### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าข้อมูลศูนย์ Tab ข้อมูลทั่วไป ปรับแก้หัวข้อชื่อ...

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#62]
![image](https://user-images.githubusercontent.com/30930235/32767290-50b16b68-c945-11e7-848c-467d4546127a.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 01-19-09](https://user-images.githubusercontent.com/37333/32908160-54589272-cb35-11e7-968c-3de3f41a8aad.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
