### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - หน้าบันทึกข้อมูล แสดงชื่องานที่ทำไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#63]
![image](https://user-images.githubusercontent.com/30930235/32767506-40df66e4-c946-11e7-92d5-df512424abea.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-15](https://user-images.githubusercontent.com/37333/32824530-e84587b0-ca13-11e7-9d94-7c63e1a04ed5.png)
![screenshot-2017-11-15 2](https://user-images.githubusercontent.com/37333/32824533-e9efa582-ca13-11e7-8ed7-a3dd2d1d060b.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย ขอบคุณคะ
