### ISSUE TITLE
Back : ศ.อื่นๆ หน้าจอบันทึก ข้อมูลทั่วไป ปรับแก้หัวข้อ ประเภท

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#64]
![image](https://user-images.githubusercontent.com/30930235/32767713-2eaa4560-c947-11e7-842f-bee40e510918.png)

**Comment by Srikridsadaporn** [comment]
ขอปิดเพื่อตรวจสอบก่อน
