### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - หน้าบันทึกข้อมูล สลับตำแหน่งการแสดงหัวข้อ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#65]
![image](https://user-images.githubusercontent.com/30930235/32767905-17520b86-c948-11e7-9183-eb55e87e87db.png)

**Comment by cmmadnat** [comment]
<img width="920" alt="screen shot 2560-11-15 at 14 37 48" src="https://user-images.githubusercontent.com/37333/32824184-8ed82c56-ca12-11e7-9b00-44c5453a130d.png">

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
