### ISSUE TITLE
Back : ศ.อื่นๆ หน้าจอบันทึก Tab ข้อมูลทั่วไป ปรับแก้หัวข้อ รางวัล

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#66]
![image](https://user-images.githubusercontent.com/30930235/32768056-c0ae595a-c948-11e7-9d96-24a3125da208.png)

**Comment by cmmadnat** [comment]
ขอทบทวนในที่ประชุมครับเรื่องการจัดเรียง ดูจากหลาย ir แล้วไม่เข้าใจ ขอโทษนะครับ

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
