### ISSUE TITLE
Back : ศ.อื่นๆ หน้าจอบันทึก Tab ข้อมูลทั่วไป ปรับแก้หัวข้อ ปีที่จัดตั้ง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#67]
![image](https://user-images.githubusercontent.com/30930235/32768150-25ff3c70-c949-11e7-94bb-5a6c4d0d1560.png)

**Comment by cmmadnat** [comment]
ให้สลับที่ใช่ไหมครับ

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
