### ISSUE TITLE
Back : ศ.อื่นๆ หน้าจอบันทึก Tab ข้อมูลทั่วไป ปรับแก้การแสดงหัวข้อบรรทัดที่ 3

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#68]
![image](https://user-images.githubusercontent.com/30930235/32768246-a0bff1ac-c949-11e7-96f0-215a86650608.png)

**Comment by cmmadnat** [comment]
ตรงนี้ไม่แน่ใจว่าหมายความว่าให้เพิ่มช่องชื่อ "รหัสศูนย์ต้นสังกัด" แล้วย้ายที่วางสถานะศูนย์เรียนรู้ กับสถานะข้อมูลรึเปล่าครับ

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
