### ISSUE TITLE
Back : ศ.อื่นๆ หน้าจอบันทึก Tab ข้อมูลทั่วไป ขยายช่องแสดงรายละเอียด

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#69]
![image](https://user-images.githubusercontent.com/30930235/32768466-805faadc-c94a-11e7-8b76-cf3bee1a93d1.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 01-14-05](https://user-images.githubusercontent.com/37333/32907966-a070d1c0-cb34-11e7-8ef4-cc51d9e6cf42.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
