### ISSUE TITLE
Back : ศูนย์เรียนรู้เศรษฐกิจพอเพียง- หน้าจอบันทึกข้อมูลเอกสารประกอบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#7]
@cmmadnat  รบกวนปรับตามรายลละเอียดในภาพ

![image](https://user-images.githubusercontent.com/31124544/32319611-c3ea2310-bfed-11e7-89a2-ff3ac738a38a.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32477769-13e550d8-c3b3-11e7-9a30-a2559ec29db8.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
