### ISSUE TITLE
Back : ศ.ตามแนว หน้าจอบันทึก Tab ข้อมูลทั่วไป ขยายขนาดชื่อกลุ่ม

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#70]
![image](https://user-images.githubusercontent.com/30930235/32768815-054ab4ca-c94c-11e7-938f-899b80357004.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 01-12-59](https://user-images.githubusercontent.com/37333/32907920-7a85989c-cb34-11e7-9d83-5e8a3e90a1cf.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
