### ISSUE TITLE
Back : ศ.ตามแนว หน้าจอบันทึก Tab ข้อมูลทั่วไป ปรับปรุงการแสดงหัวข้อ ศูนย์ศึกษาการพัฒนา

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#71]
![image](https://user-images.githubusercontent.com/30930235/32768941-79a7afee-c94c-11e7-9b64-0f2230ece6cc.png)

**Comment by cmmadnat** [comment]
เปลี่ยนให้เหมือนกับศูนย์เรียนรู้ประเภทอื่นนะครับ
![screenshot from 2017-11-17 01-10-37](https://user-images.githubusercontent.com/37333/32907852-2bf1cb42-cb34-11e7-84a9-13a48f5f9fb1.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
