### ISSUE TITLE
Back : ศ.ตามแนว หน้าจอบันทึก Tab ข้อมูลทั่วไป ปรับแก้การแสดงหัวข้อบรรทัดที่ 2

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#72]
![image](https://user-images.githubusercontent.com/30930235/32769071-f7457436-c94c-11e7-981a-f65b49ea5941.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 01-08-04](https://user-images.githubusercontent.com/37333/32907787-d9ab3198-cb33-11e7-8639-e1aa22d9f0ca.png)

**Comment by RDPB2-Kuer** [comment]
ปรับแก้เรียบร้อย
