### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - Tab เอกสารประกอบ ปรับแก้รูปแบบเอกสารที่อัพโหลด

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/rdpb2#73]
![001](https://user-images.githubusercontent.com/33414080/32771207-98f5aa2e-c954-11e7-8c1f-06dadd5da23e.PNG)

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
