### ISSUE TITLE
Back : ศูนย์เรียนรู้ตามแนวพระราชดำริ หน้าจอบันทึกข้อมูลที่ตั้ง ปรับแก้ฟิลด์บังคับ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#74]
![image](https://user-images.githubusercontent.com/31124544/32815457-c3c976e4-c9e6-11e7-8aea-b7ab98f33a39.png)

**Comment by cmmadnat** [comment]
<img width="935" alt="screen shot 2560-11-15 at 14 32 02" src="https://user-images.githubusercontent.com/37333/32823990-c11be3d4-ca11-11e7-9825-c68c928ab38a.png">

**Comment by Srikridsadaporn** [comment]
ตอนนี้ยังไม่เห็นการเปลี่ยนแปลง รอให้น้องแนต Update ระบบก่อน

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
