### ISSUE TITLE
ฺBack : ศูนย์เรียนรู้เศรษฐกิจพอเพียง หน้าข้อมูลทั่วไป : ปรับสีฟอนท์ให้เหมือนกัน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#75]
![image](https://user-images.githubusercontent.com/31124544/32816819-4e7fe006-c9ed-11e7-89be-27253bc2bde4.png)

**Comment by cmmadnat** [comment]
<img width="431" alt="screen shot 2560-11-15 at 14 29 49" src="https://user-images.githubusercontent.com/37333/32823922-6d6aa0a4-ca11-11e7-8ae5-2361f3f7f038.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
