### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง - หน้าบันทึกข้อมูล เพิ่มเส้นปิด Block

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#76]
![image](https://user-images.githubusercontent.com/31124544/32828522-ecc2d2bc-ca21-11e7-9fa0-e020b07f9166.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 01-04-02](https://user-images.githubusercontent.com/37333/32907624-3a5e03fe-cb33-11e7-833d-44b2ac9d2852.png)

**Comment by RDPB2-Kuer** [comment]
ยังมีอีกแห่งหนึ่งที่มีปัญหาเช่นเดียวกัน
![image](https://user-images.githubusercontent.com/30930235/32950168-01b84db6-cbd8-11e7-8d2f-4ecf86a77fab.png)

**Comment by anucha1892** [comment]
ทดสอบ 20/11/60 
ยังไม่แก้ไข เส้นขอบ อำเภอ/เขต ครับ

**Comment by Srikridsadaporn** [comment]
เพิ่มเส้นปิดทั้ง 2 ตำแหน่งแล้ว ปิด
