### ISSUE TITLE
ฺBack : ศูนย์เรียนรู้ตามแนวฯ - หน้าจอบันทึกข้อมูล การเลือกประเภท

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#77]
![image](https://user-images.githubusercontent.com/31124544/32871368-368520b2-cab3-11e7-8a05-8c066cc9a102.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 01-05-59](https://user-images.githubusercontent.com/37333/32907708-8cc877fa-cb33-11e7-84ef-52ca80b68201.png)

**Comment by RDPB2-Kuer** [comment]
OK
