### ISSUE TITLE
Bฺack : ศูนย์เรียนรู้ตามแนวพระราชดำริฯ  หน้าบันทึกข้อมูล - ปรับฟิลด์บังคับ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#78]
น้องแนตคะ รบกวนปรับตามภาพด้านล่าง
![image](https://user-images.githubusercontent.com/31124544/32875554-357f7bd2-cacb-11e7-9380-7b30f28590ae.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 00-46-40](https://user-images.githubusercontent.com/37333/32906847-cc1f5408-cb30-11e7-83ef-665c372748be.png)

**Comment by RDPB2-Kuer** [comment]
OK
