### ISSUE TITLE
Bฺack : ศูนย์เรียนรู้ตามแนวพระราชดำริฯ หน้าบันทึกข้อมูล - การเลือกภาพที่ตั้งศูนย์ใช้งานไม่ได้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#79]
![image](https://user-images.githubusercontent.com/31124544/32875999-48c9911c-cacd-11e7-8858-872dfb672d0c.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 00-45-40](https://user-images.githubusercontent.com/37333/32906798-a8714ff2-cb30-11e7-9582-47f4d3f06d8b.png)

**Comment by anucha1892** [comment]
เรียบร้อยครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
