### ISSUE TITLE
Back : ศูนย์เรียนรู้ตามแนวพระราชดำริ- หน้าจอการแสดงรายการ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#8]
น้องแนต @cmmadnat  รบกวนปรับตามรายละเอียดในภาพ
![image](https://user-images.githubusercontent.com/31124544/32323355-4e51d71c-bffa-11e7-9699-a53e6fb759e7.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32359686-5eb68098-c082-11e7-8763-19e7e79fd15a.png)

**Comment by cmmadnat** [comment]
แำ้ไขเพิ่มเติมส่วนของถัดไปก่อนหน้าหน้าสุดท้ายหน้าแรก

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
