### ISSUE TITLE
Back : ศ.ตามแนวพระราชดำริฯ - หน้าบันทึกข้อมูล เรียงลำดับและปรับสี Icon

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#80]
![image](https://user-images.githubusercontent.com/31124544/32876224-7089542a-cace-11e7-9f8d-fac5afac4cf3.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 00-40-00](https://user-images.githubusercontent.com/37333/32906578-deffeade-cb2f-11e7-92b5-e6c4b889ad8f.png)

**Comment by RDPB2-Kuer** [comment]
ยังไม่เรียบร้อย ขนาด icon ที่ปรับใหม่ไม่เท่ากัน
![image](https://user-images.githubusercontent.com/30930235/32950345-98d5c9d0-cbd8-11e7-80ad-6dd0742ccf6d.png)

**Comment by anucha1892** [comment]
ทดสอบ 20/11/60
ขนาด Icon ยังไม่เท่ากัน

**Comment by RDPB2-Kuer** [comment]
OK
