### ISSUE TITLE
Back : ศ.ตามแนวพระราชดำริฯ - หน้าเอกสารประกอบ คำอธิบายไม่แสดง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#81]
![image](https://user-images.githubusercontent.com/31124544/32876842-3e7559b8-cad1-11e7-9508-afd444f87c52.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 00-38-16](https://user-images.githubusercontent.com/37333/32906513-a26314b6-cb2f-11e7-88eb-f5b25e8a7290.png)

**Comment by RDPB2-Kuer** [comment]
ขอให้ปรับแก้ให้เหมือนที่แจ้งในศ. อันอื่น

**Comment by anucha1892** [comment]
![81](https://user-images.githubusercontent.com/33414080/33001855-11f36dac-cde3-11e7-9cb0-bb5fb14849a3.PNG)

**Comment by Srikridsadaporn** [comment]
ปรับแก้แล้ว ปิด
