### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าแสดงรายการ ปรับสีปุ่ม 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#82]
![image](https://user-images.githubusercontent.com/31124544/32877157-ca575552-cad2-11e7-9b91-71dd0037ca5b.png)

**Comment by cmmadnat** [comment]
![screenshot from 2017-11-17 00-36-06](https://user-images.githubusercontent.com/37333/32906388-5a534d1c-cb2f-11e7-80d4-c89aa2f62618.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
