### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าแสดงรายการ  ปรับขนาดฟอนท์

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#83]
![image](https://user-images.githubusercontent.com/31124544/32877256-29e9e43a-cad3-11e7-8a84-6c163e1c6f08.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32905821-aea2a3a6-cb2d-11e7-8ea8-ed5f8408d5f7.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
