### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าเพิ่มข้อมูล ปรับสีปุ่มยกเลิก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#84]
![image](https://user-images.githubusercontent.com/31124544/32877474-4b2c046a-cad4-11e7-9439-977be6f4555a.png)

**Comment by cmmadnat** [comment]
<img width="342" alt="screen shot 2560-11-16 at 22 22 44" src="https://user-images.githubusercontent.com/37333/32899114-b0ae4e40-cb1c-11e7-8b4e-39dfec30c1f3.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
