### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าบันทึกข้อมูล  ปรับแก้วิธีการระบุการเลือก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#85]
![image](https://user-images.githubusercontent.com/31124544/32881448-d82b96a0-cae3-11e7-9cae-e817646988c7.png)

**Comment by cmmadnat** [comment]
ตรงรางวัลขัดกันกับ #86 จะใช้ของอันนั้นคือ - นะครับ

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
