### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าบันทึกข้อมูล - ปรับแก้ฟิลด์รางวัล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#86]
![image](https://user-images.githubusercontent.com/31124544/32881983-7d6e7d84-cae5-11e7-8947-f0603397a7ea.png)

**Comment by cmmadnat** [comment]
<img width="458" alt="screen shot 2560-11-16 at 21 59 25" src="https://user-images.githubusercontent.com/37333/32897948-6f86bf2c-cb19-11e7-96c3-1a1cf1f59817.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
