### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าบันทึกข้อมูล - ปรับแก้ฟิลด์บังคับสถานที่ตั้ง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#87]
![image](https://user-images.githubusercontent.com/31124544/32882085-c3c949b2-cae5-11e7-8416-93e48c919140.png)

**Comment by cmmadnat** [comment]
<img width="1020" alt="screen shot 2560-11-16 at 21 56 43" src="https://user-images.githubusercontent.com/37333/32897784-1004ab72-cb19-11e7-8999-73fd0d83dd67.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
