### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าบันทึกข้อมูล - รูปแผนที่ตั้งศูนย์ยังใช้งานไม่ได้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#88]
![image](https://user-images.githubusercontent.com/31124544/32882241-4d3d4338-cae6-11e7-9a4f-789cf2239879.png)

**Comment by cmmadnat** [comment]
<img width="541" alt="screen shot 2560-11-16 at 21 54 34" src="https://user-images.githubusercontent.com/37333/32897633-c203428a-cb18-11e7-99d9-312e5568fa44.png">
fix

**Comment by RDPB2-Kuer** [comment]
OK
