### ISSUE TITLE
Back : ศ.อื่นๆ - หน้าบันทึกข้อมูล - ปรับปรุงฟิลด์บังคับข้อมูลการติดต่อ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#89]
![image](https://user-images.githubusercontent.com/31124544/32882398-cdfa1dde-cae6-11e7-9271-0ba1398edcb4.png)

**Comment by cmmadnat** [comment]
<img width="564" alt="screen shot 2560-11-16 at 21 45 31" src="https://user-images.githubusercontent.com/37333/32897188-7fa86cc2-cb17-11e7-8102-1f9415ed845d.png">

**Comment by RDPB2-Kuer** [comment]
ขอโทษที่ทำให้เข้าใจผิด เนื่องจากผู้รับผิดชอบศูนย์เป็นเงื่อนไขการค้นหา จึงต้องเป็น Field บังคับให้ใส่ข้อมูล

**Comment by anucha1892** [comment]
ทดสอบ 20/11/60 
"ผู้รับผิดชอบศูนย์เรียนรู้" ยังไม่ได้แก้ให้เป็นฟิลด์บังคับ "*"

**Comment by Srikridsadaporn** [comment]
น้องแนตคะ รบกวนปรับ "ผู้รับผิดชอบศูนย์เรียนรู้" เป็นฟิลด์บังคับ ขอโทษคะ พี่ผิดเอง

**Comment by cmmadnat** [comment]
<img width="510" alt="screen shot 2560-11-21 at 16 58 15" src="https://user-images.githubusercontent.com/37333/33066185-34ac88d8-cedd-11e7-9dfc-b40d60b511b3.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย
