### ISSUE TITLE
Back :ศูนย์เรียนรู้ตามแนวพระราชดำริ- หน้าจอบันทึกข้อมูลทั่วไป

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#9]
@cmmadnat รบกวนปรับตามรายลละเอียดในภาพ

![image](https://user-images.githubusercontent.com/31124544/32321319-540637fe-bff3-11e7-81ca-e469211afc1f.png)

**Comment by cmmadnat** [comment]
แก้ไขแล้วครับ
![image](https://user-images.githubusercontent.com/37333/32360984-d633a672-c08d-11e7-9771-3a1cec5ce6b4.png)

**Comment by RDPB2-Kuer** [comment]
ไม่เอาแบบนี้ได้ไหมคะ ทำเหมือนกับ การ เลือกผู้ตรวจในระบบเขือน ของกรมชลได้ไหมคะ

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32479195-46e734f8-c3bb-11e7-9008-9c053eb4ce28.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
