### ISSUE TITLE
ฺBack : ศูนย์ศึกษาการพัฒนา หน้าเพิ่มข้อมูล ปรับสีปุ่ม "ยกเลิก"

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#90]
![image](https://user-images.githubusercontent.com/31124544/32884389-bdce236e-caec-11e7-904b-4d16aa4942f6.png)

**Comment by cmmadnat** [comment]
<img width="1042" alt="screen shot 2560-11-16 at 21 43 17" src="https://user-images.githubusercontent.com/37333/32897059-3045312e-cb17-11e7-818a-d795396fad42.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
