### ISSUE TITLE
ฺBack : ศูนย์ศึกษาการพัฒนา หน้าเพิ่มข้อมูล ปรับปรุงฟิลด์บังคับ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#92]
![image](https://user-images.githubusercontent.com/31124544/32884742-f24aa92c-caed-11e7-9d3d-6d48c01ac384.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-16 2](https://user-images.githubusercontent.com/37333/32885109-18e1bdb8-caef-11e7-9dd0-2c05a794649f.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
