### ISSUE TITLE
ฺBack : ศูนย์ศึกษาการพัฒนา หน้าเพิ่มข้อมูล ตรวจสอบรูปแบบของอีเมล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#93]
![image](https://user-images.githubusercontent.com/31124544/32885179-51a1d6e2-caef-11e7-8650-1500a1a899a8.png)

**Comment by cmmadnat** [comment]
<img width="410" alt="screen shot 2560-11-16 at 21 41 23" src="https://user-images.githubusercontent.com/37333/32896945-f281e51c-cb16-11e7-86ed-c78761c33b74.png">
<img width="444" alt="screen shot 2560-11-16 at 21 41 37" src="https://user-images.githubusercontent.com/37333/32896947-f2d235f8-cb16-11e7-9bee-bb0c22b95173.png">
d

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/32953171-0342ac44-cbe2-11e7-9fd3-1c98465e32e9.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32989229-d1dd6f72-cd44-11e7-9828-eaefe3cf19d6.png)

**Comment by RDPB2-Kuer** [comment]
OK
