### ISSUE TITLE
ฺBack : ศูนย์ศึกษาการพัฒนา ตรวจสอบฟิลด์บังคับหน้าเพิ่มข้อมูล 

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#94]
![image](https://user-images.githubusercontent.com/31124544/32885306-b96ff3da-caef-11e7-95e4-279af1ffb266.png)

**Comment by cmmadnat** [comment]
<img width="1025" alt="screen shot 2560-11-16 at 21 36 33" src="https://user-images.githubusercontent.com/37333/32896671-3e425bc2-cb16-11e7-9344-086f3229d5d6.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
