### ISSUE TITLE
ฺBack : ศูนย์ศึกษาการพัฒนา ฯ -  หน้าแสดงรายการ  เอาเวลาออก

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#95]
![image](https://user-images.githubusercontent.com/31124544/32934438-5ec668e2-cb9e-11e7-9270-72bcc9ff14b6.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-17](https://user-images.githubusercontent.com/37333/32937931-1514cf0e-cbad-11e7-8a63-083c2d13bec0.png)

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
