### ISSUE TITLE
Back : ศูนย์ศึกษาการพัฒนา ฯ - หน้าเอกสารประกอบ ยังไม่แสดงคำอธิบาย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/rdpb2#96]
![image](https://user-images.githubusercontent.com/31124544/32934910-3270b82c-cba0-11e7-9685-010eda5c51ea.png)

**Comment by cmmadnat** [comment]
![screenshot-2017-11-17 2](https://user-images.githubusercontent.com/37333/32937883-d14c73c6-cbac-11e7-80c3-44d789057ac2.png)

**Comment by RDPB2-Kuer** [comment]
ขอปรับแก้เพิ่มเติม ดังนี้
![image](https://user-images.githubusercontent.com/30930235/32978479-7ff2f9c2-cc75-11e7-855e-96933658424c.png)
