### ISSUE TITLE
Back : ศ.เศรษฐกิจพอเพียง Clear ฐานข้อมูลแล้ว ยังมีค่าค้างอยู่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#97]
![image](https://user-images.githubusercontent.com/30930235/32950053-8a928e36-cbd7-11e7-8997-498e5dd1c374.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อยค่ะ
