### ISSUE TITLE
Back : ศ. ตามแนวพระราชดำริ หน้าบันทึก หัวข้อศูนย์ศึกษาการพัฒนา ให้ระบุ "เลือก" 

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#98]
![image](https://user-images.githubusercontent.com/30930235/32950497-1c82fd0c-cbd9-11e7-9a5f-8fc8cb21aa67.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32989055-02374014-cd43-11e7-916b-5a66c66682ef.png)

**Comment by RDPB2-Kuer** [comment]
OK
