### ISSUE TITLE
Back : ศ. ตามแนวพระราชดำริ บันทึกข้อมูล หัวข้อ ประเภท ยังไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/rdpb2#99]
![image](https://user-images.githubusercontent.com/30930235/32950891-94e48490-cbda-11e7-838c-75b119b486b3.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/32988997-7741b93a-cd42-11e7-903c-1e74b877a2f4.png)
มันเป็น placeholder ครับต้องเป็นสีนั้น จะได้รู้ว่ายังไม่ได้เลือก คล้ายกับช่อง search แบบนี้ถูกแล้วครับ

**Comment by anucha1892** [comment]
![99](https://user-images.githubusercontent.com/33414080/33002362-50153df6-cde6-11e7-9ff7-a84f366a0f2f.PNG)

**Comment by anucha1892** [comment]
เพิ่มเติมครับ กรณีเลือกชื่อกลุ่ม/เกษตรกร ที่เคยมีชื่ออยู่ในระบบแล้ว ระบบแสดงผลไม่ถูกต้อง ดัังภาพ
![99-1](https://user-images.githubusercontent.com/33414080/33002788-f1017818-cde8-11e7-8a41-d239ca423487.PNG)
![99-2](https://user-images.githubusercontent.com/33414080/33002793-f79c3596-cde8-11e7-82d4-16db1ee48b10.PNG)

**Comment by RDPB2-Kuer** [comment]
OK
